### ISSUE TITLE
ERROR DCAStrategyRunner

### ISSUE THREAD

**Issue by OatmealTokyo** [taniman/profit-trailer#1054]
Hi. I restarted my computer and notice the following error in terminal.
ERROR DCAStrategyRunner - An error occured

This keeps repeating.  Currently I have: 2 Pending Log items 4 DCA items and 4 pairs log.  It is my understanding this error occurred because of a corrupt file?  

How should I resolve without effecting my DAC items.  Thank you.

**Comment by mcbweb** [comment]
I am having the same issue i think.... DCAStrategyRunner - API Problems?

**Comment by mcbweb** [comment]
on Bittrrex by the way... ever since the update i notice way more API issues now

**Comment by nstefi** [comment]
I also have these API key problems on Bittrex starting about 12 days ago. I have a pair in DCA for 12 days and it cannot buy anything for DCA because it sees my balance as zero, which is wrong. I already discussed this with support and there is nothing wrong with my settings, I have way more balance left than needed.
I already downgraded the bot to version 14 then 12, and started with from scratch without JSON file and didn't help. Maybe Bittrex changed something about their APIs, and PT needs to be updated to show the correct balance. This only happens when DCA tries to buy, but the balance in the top bar is correct.
I noticed this on Bittrex's Developer's Guide page:
DEPRECATING
Request:
https://bittrex.com/api/v1.1/account/getbalances?apikey=apikey

Maybe PT is still using that way to query the balance?

**Comment by Cryptomi** [comment]
same problem on bittrex.

**Comment by taniman** [comment]
For support update to v.15 and ask for support on discord. this is for bugs

**Comment by nstefi** [comment]
I already asked support a ton of times, this is a bug
