### ISSUE TITLE
Pair Log and Pending Log Not Displaying Coins - Binance 

### ISSUE THREAD

**Issue by kenjb** [taniman/profit-trailer#1135]
Hi.  We recently setup PT for Binance.  It immediately stared buying but no coins show up in the Pairs Log or in the Pending Log.   We do have coins in the DCA Log and Sales Log.  

![image](https://user-images.githubusercontent.com/34899879/36337772-6c2b4492-136c-11e8-964a-0e7e9c507a82.png)
![ptpairslog](https://user-images.githubusercontent.com/34899879/36337775-8048fece-136c-11e8-93df-af2b75213f1e.jpg)

**Comment by SgtBatten** [comment]
I bet you have all DCA enabled = true.

So nothing will go to pairs because it automatically goes to dca.

Younhave to set a percentage at which pairs go timecard if you want to see them in pairs.

All DCA enabled = -1.7 for example

Please ask questions like this in discord. This is not a support platform. It is for bugs

**Comment by kenjb** [comment]
thank you and sorry for posting here.
