### ISSUE TITLE
USDT and ETH ticker on dashboard 

### ISSUE THREAD

**Issue by mfcholdings** [taniman/profit-trailer#1191]
could you replace the BTC ticker you see in the pictures with USDT and ETH when usng them.. 
![1](https://user-images.githubusercontent.com/36377757/36455617-3569e282-16a1-11e8-8cf0-b45760c4289e.png)
![2](https://user-images.githubusercontent.com/36377757/36455618-358b1ea2-16a1-11e8-90ec-3c04a606ac69.png)

**Comment by ShadowOnTheLand** [comment]
Well the USDT Value is almost always going to be 1 or very close to it, so that kinda defeats the purpose.

ETH has some merit. But considering that BTC is the driving factor of the crypto-market, even though ETH can run seperate from BTC, it's rather rare.

Until BTC is no longer the main driving force in the crypto world, BTC will decide where prices go.

**Comment by networkjackbb** [comment]
Thanks for making that decision for us. If I choose ETH as my base currency, I really don't care about BTC.

There is an underlying precept for software design that should be embraced:

"We may not know who the user is, but we know it isn't us."

**Comment by djcrypto75** [comment]
The ETHUSD price is in the ticker.

**Comment by networkjackbb** [comment]
I can plainly see the ETHUSD price is in the ticker. Thanks.
