### ISSUE TITLE
Bot constantly giving this new error

### ISSUE THREAD

**Issue by XcidTrader** [taniman/profit-trailer#1275]
<img width="1124" alt="screen shot 2018-02-26 at 08 38 59" src="https://user-images.githubusercontent.com/35023898/36656421-054a24f2-1ad1-11e8-8bc6-441170e9eda2.png">

Hi guys,

Running Binance, PT and PTF. The latest version.
It constantly needs to be restarted .

Ive checked my time settings in the both PT and windows. I dont see anywhere to change time in PTF.

Please see attached error. Nothing is visible in the terminal console but I can see with the GUI add-on that its not working. Graphs charts become stagnant in profit% 

Thanks,
Stu

Image Reference to error: 
https://user-images.githubusercontent.com/35023898/36656421-054a24f2-1ad1-11e8-8bc6-441170e9eda2.png

**Comment by taniman** [comment]
If you do not get an error in your log saying you need to restart, that means the bot is not hanging. 
That's if you are on version 1.2.6.19

Not because a gui plugin says the bot is hanging means it's hanging. We have seen multiple time that this gui gives false signals

prices do not continually change especially seeing 3 out of 4 prices are on a very low volume
