### ISSUE TITLE
DCA not enough coins bug

### ISSUE THREAD

**Issue by vincev1975** [taniman/profit-trailer#1278]
When I set buy_available_volume_trigger bigger than zero (like 10,20 50 etc) I always get an error 'There are not enough coins in the orderbook for a full DCA on XRPBTC at needed price'.  It is only trying to DCA 0.02 size on a very high volume coin so the order volume of 10 should be available.  When I set it to zer the error is gone.  Here is a screenshot after setting it from zero to 10:
https://www.screencast.com/t/0gQwtgL1

Many people reported this issue on the PT Discord thread.  The issue is that you are not reading or interpreting the orderbook volume correctly.  Please fix this issue for next release.

**Comment by magisterh** [comment]
Same problem, v19

**Comment by YoJeff** [comment]
Have you actually watched the order book to verify?   "Should be available" != "not interpreting the orderbook correctly."

**Comment by yuvalbar84** [comment]
Support ticket reference: #559377

**Comment by dmalcolm** [comment]
Agree I am seeing it a lot on the Binance BTC bot. "There are not enough coins in the orderbook to do a FULL DCA for REQBTC at needed price"

**Comment by magisterh** [comment]
The message comes when the coin goes below the ALL_min_buy_volume value...  I changed the value from 500 to 200 and the bot immediately executed DCA for 2 coins.

**Comment by dmalcolm** [comment]
After changing based on @magisterh suggestion I noticed the reason for me this is happening is some of my old DUST actually made it into DCA section.  Since this DUST changed to DCA based on the market changes you will not be able to buy more as the DUST volume is too low. 

I have chosen to lower my min buy volume.  

Others may choose to adjust their DUST levels in the appSettings.

**Comment by TheBigShort111** [comment]
Yet another reason that there should be a control to exclude DUST from trading. It seems to me that including DUST is way more hassle than it's worth. It risks losses on full trades to recover pennies because it's original buy price sets the buy price of the whole order, or in the case above, it sets the buy price for the DCA... Please include a control to exclude DUST from all trades and let people choose whether or not to include it in a trade.

**Comment by mayday79** [comment]
I experience the same Problem with .20

![pt20](https://user-images.githubusercontent.com/8648400/37004058-6c5aea88-20cf-11e8-950c-e11742d1d996.PNG)

**Comment by sevenstyles** [comment]
Same here ' There are not enough coins in the orderbook to do a FULL DCA '

**Comment by taniman** [comment]
Have you thought about the fact that there is indeed not enough coins to do a full DCA? If anyone could show me a screenshot of this message being display and an orderbook full of coins to buy at the needed price I will look further into this. Else I will close this issue

**Comment by mayday79** [comment]
Hi Taniman, question... how do I find out what the BOT's "needed price" is?

2 Screenshots I just made now:

![message](https://user-images.githubusercontent.com/8648400/37059840-be9acf06-218e-11e8-8954-768170f69327.PNG)
![orderbook](https://user-images.githubusercontent.com/8648400/37059845-c31c6120-218e-11e8-8fc9-07efc078874d.PNG)

**Comment by kaotic818** [comment]
I also noticed there is a 12-30 second delay in the price on binance and PT. This is a re occurring issue still not fixed.





________________________________

**Comment by sevenstyles** [comment]
It seems then when a coin in DCA falls below your set 'All_min_buy_volume', it puts it into SOM and then throws the message 'There are not enough coins in the orderbook to do a FULL DCA' when it attempts to DCA. I don't want to have to lower my ''All_min_buy_volume'' so that coins below that value can DCA. 

Some coins in DCA fall considerably below my ''All_min_buy_volume' level and then constantly throws that order book message. I added in '"DcaBuyAvailableVolumeTrigger": "50", but I think because once it puts it into SOM in DCA this then does not do anything?

**Comment by sevenstyles** [comment]
I am getting the same combo of errors with Mayday79 above. As soon as I adjusted my ''All_min_buy_volume'', it DCAd. but thanks for the valuable insight YoJeff.


![untitled-1](https://user-images.githubusercontent.com/36907877/37067616-bba98a9c-21fe-11e8-94b0-8b4c35fbed51.jpg)

**Comment by SgtBatten** [comment]
There is nothing in PT that automatically puts one coin in SOM. it's all or none and has nothing to do with anything except BTC 24 hour trend.

That message you see quite clearly states there is not enough volume in the orderbook. meaning there are not enough coins for sale at the lowest sell price for you to achieve a successful DCA.

too keep this issue on topic and answer @vincev1975 , the bot cannot DCA at less than 100% anyway. so setting buy_available_volume_trigger to less than 100 is pointless. People should also be aware that leaving at default 100 will result in partial fills. setting it to more than 100% is recommended.

**Comment by taniman** [comment]
@mayday79  to answer your question. 

if you look at the bot you see current ask price is 0.0002392 and you own 9.74 (PT Screenshot)
on binance you see the lowest ask is 0.0002394 and amount 4.06

So the bot could not buy at that moment because the bot wanted a lower price of 0.0002392 but that was already sold.

but even if we were to try and buy at 0.0002394 that would also not work. 
cause in the orderbook there is only 4.06 and we need 9.74

So you see the order book is low on coins and that explains the info message.
It's just a matter of giving the bot a chance to buy at the right price
