### ISSUE TITLE
Port in use?

### ISSUE THREAD

**Issue by BaliDog** [taniman/profit-trailer#1333]
Hi there, when starting up PT I get this error:

 22:05:11 INFO Application - PT Version: 1.2.6.20
2018-03-01 22:05:12 INFO Application - Java Version: 1.8.0_151
2018-03-01 22:05:12 ERROR Application - **Port 8081 is in use, close the program using this port or try setting server.port (application.properties) to a different port.**

Any advice on how to fix it? Is it an update issue? Many thanks!

**Comment by twig123** [comment]
Github issues it for reporting bugs with the bot. Issues with getting your bot started should be addressed via a support ticket, or Discord.

However, your issue is that either you already have a copy of the bot running, or some other program is already running and using port 8081. Restart your computer and try starting the bot again. if it gives you the same error... edit the application.properties file and change the port number to a different port number.

**Comment by BaliDog** [comment]
OK. Thanks for all that. I will give it a go and follow the other channel if the problem persists.

Cheers,

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
