### ISSUE TITLE
ema_cross_direction + only closed candles

### ISSUE THREAD

**Issue by taniman** [taniman/profit-trailer#1344]

**Comment by Steven-Licari** [comment]
Can you give us some more info other that it will be available in V2.0, when will that be available, I see no updates on the wiki?

**Comment by taniman** [comment]
There is no info to give on this as its just an idea that I was thinking about and might not even be added

**Comment by TheBigShort111** [comment]
Would it be possible for a straight EMA cross strategy on both the buy and sell sides? In other words, no forward or back looking at candles... The only candle that would matter would be the trigger candle on the buy and the sell side (the candle where the cross happens)

EMA Cross is not the most effective method in day trading stocks as the volatility is not there, and trading fees are high... However, in crypto, the volatility is a perfect match for trading a straight EMA cross strategy. In declining markets buys will be lower than if using EMASPREAD, as more often than not, the downward trend usually has small upward movement (not enough to cross the EMA slow line, but enough to trigger a buy even when the price continues to drop. With a straight EMA cross strategy, the buy happens once the fast EMA crosses up the slow EMA, then sell when the opposite condition is met... This results in exploiting much of the total gain during a bull run, and mitigates holding bags as the sell happens when the fast EMA drops below the slow EMA and will not buy again till the EMA's cross again at the next bottom.

There would be instances of small partial trading fee losses, however the gains greatly outweigh any small, fractional, insignificant losses.

Using this method allows the most gain during bull runs as there is no predetermined "gain" percentage (plus any trailing) factored into the equation. Quite frankly speaking, this seems to be the best strategy for trading crypto, since it is so volatile.

No buys on the way down, regardless of the percentage drop, no DCA bags... Plus the benefit of capitalizing on all the gain on the up swings.

If nothing else, it would be nice to have it as a sell option.

**Comment by Steven-Licari** [comment]
Thanks for the reply it seems as if the PT team is blowing this request off and had several others requesting the same thing.

They could make this a pay for update and I'm sure the community would have no problem paying for it.  The bags are what chase people away from PT going with the EMACROSS buy/sell gets rid of the bags

**Comment by TheBigShort111** [comment]
Honestly, I don't think this is something they are blowing off. I'm optimistic that they have heard the call for this as a sell strategy. My impression is that they focus attention to known issues first (rightfully so) then address the issues and features that they feel would benefit the community the most. That said, I do think a lot of effort has gone into making PT better and better, version after version, BUT, I think some of that effort has gone into things that people have requested that are quite useless in the crypto world.

For example... High BB as a sell strategy? - High BB is frankly quite useless in the crypto world on the sell side as the volatility of the market is too high for it to be useful in any way. Candles will always break out early using high BB in a volatile market, which is why it is frowned upon by crypto day traders. But people have a love fest with BB as a craay over from the "investment" world. As an indicator, it one thing to look at in combination with other TA for verification of a trend, but by no means should it be used as a buy trigger alone. But for whatever reason, people "want" the "ability" to have BB till they use it and find it simply does yield great results.

When the devs decide to experiment with EMACROSS, I'm willing to beta test it on a live account to prove is worthiness as a strategy. (that's an open invitation to the devs) - And now that feeder can utilize different strategies depending on market conditions, it would be amazing to be able to use EMACROSS for the bull markets.

Gain as a strategy is pretty straight forward and very basic, but misses a lot of the gain on many bull runs. Gain is a double edge sword... Set your trailing high enough to ride out the small dips and you may get lucky enough to make a further gain, however some of that gain get erased due to the higher trailing amount. Set the profit too high and you miss the sell completely. So gain is a crap shoot at best. It works as advertised, but it gives up potential profit.

In the crypto space, EMACROSS on the sell side would prove the most beneficial sell strategy, especially for bull runs... As long as the EMA fast is over the slow, the bot continues to ride up... The sell happens at the cross down, which is like having a built in trailing profit. Then no buys happen on the way down till there is a cross up. Simple, elegant, and profitable. Oh, and during the big dumps, the bot rides ALL the way down, and won't buy the small bumps like it does with EMASPREAD. Unlike the typical sell strategies in PT, EMACROSS would be subject to very small occasional losses where a cross happens but does not manifest into a gain, but that is the exception rather than the rule. In general terms, EMACROSS "almost" always trades higher than the bought price, and on the rare occasion when it doesn't the loss is typically negligible. I'd accept the small fractional losses for the multi-percent profit upside each and every time! - Oh, and no more DCA bags!

In fairness, EMACROSS is not a good strategy in the typical stock market as there is not enough volatility, so most of the movement is small and incremental, which eats up money through discount and prime broker trading fees... So EMACROSS gets a bad rap from the traditional investment world... In fact, for "investing" it is a horrible strategy! But crypto is different, WAY different!... The fees are proportionately peanuts to the trade, and the volatility makes EMACROSS a great (almost optimal) selling strategy.

At the very least, it should be an option for us. On the surface it seems everything needed to implement it is already in place. The buy value is already something that is able to be set and monitored, and we already have indicator parameters that can be set, so there is already a method of determining when a cross happens, all we need is the trigger. Frankly speaking, dumping the "number of candles" would make the strategy clean and straight-forward. The lines cross here, BUY... They lines cross here, SELL.

To the devs... I am not trying to oversimplify the amount of work involved in making this happen, I'm just trying to demonstrate that for the end user it would be a very simple, and lucrative strategy. I'm willing to bet it would prove to be the most profitable PT strategy overall.

Please take me up on beta testing this on a live account... That is how confident I am in EMACROSS as a hands-off crypto sell strategy.

**Comment by YoJeff** [comment]
#884 #370 Already requested.  Already pinned to a version.  Already being worked on.    Search first and don't hijack threads.

**Comment by robheath90** [comment]
YoJeff, I have seen both of the referenced threads and although on one you have added tags, maybe you could write a comment saying this is being worked on on those threads? Seeing at this is being worked on is the best thing I've read on github since buying PT, and I've been checking regularly for just this reason. 

Looking at my long term HODLs and seeing how much they've dropped since the turn of the year has made me long for this strategy. I've manually calculated the would-be gains if I had bought and sold my coins based on EMACROSS and I'd be way closer to my dollar value at the December top than I am by HODLing.

**Comment by taniman** [comment]
@robheath90 once an issue is put on a milestone means. It's being worked on or will be worked on in that milestone. 
But to be more clear. We are currently working on milestone 2.0 so year. EMACROSS as sell strategy is coming


To anyone else that hijacked this issue. Only what I specified in my issue will be looked at. EMACROSS will currently keep working the way it is working. we will not be changing that yet.

**Comment by DragonBtc93** [comment]
Give us emacross sell with a minimum profit.

**Comment by Steven-Licari** [comment]
Can you give us a date on when this update will happen so we don’t have to hijack every EMAcross topic posted

**Comment by taniman** [comment]
There is no date. We are currently beta testing. rough estimate is 2-3 weeks

**Comment by taniman** [comment]
And you could simply not hijack each post too if you wanted. Me giving or not giving a date does not merrit hijacking posts

**Comment by Steven-Licari** [comment]
hey we want to get rich can you blame us

**Comment by Steven-Licari** [comment]
FOMO
