### ISSUE TITLE
Adding the fulfilled pending order to Sales log

### ISSUE THREAD

**Issue by cybermizrach** [taniman/profit-trailer#1415]
If I add the following lines:

ALL_pending_order_wait_time = 360
ALL_combined_cancel_pending_trigger = 0.1

PT will create a pending order for a pair. If the market trend goes upward and filled that pending order. Can PT add this sell transaction in PT's sales log so that we can report this transaction for tax purposes?

**Comment by taniman** [comment]
PT is not certified for taxes. 
PT is not aiming for that either.

If you want to report your taxes you need to create a report from your exchange transactions.

pending data are not shown in PT because they are sold by the exchange and not by the bot. 
At present moment we cannot do anything about that.
