### ISSUE TITLE
[POSSIBLE BUG] Wrong dust low amount calculation

### ISSUE THREAD

**Issue by jokaorgua** [taniman/profit-trailer#1428]
Market: USDT (BINANCE)
PT: 1.2.6.23

Bot is calculating dust amount on USDT market through bitcoin value of the coin. 
So if you buy bcc for 10$ and this will cost 0.009 btc - it will be pushed to dust log
if the price will raise to 0.0011 btc it will be NOT taken from dust log back.

[Set of screenshots(read comments under each image)](https://imgur.com/a/Jugi8)

**Comment by YoJeff** [comment]
Have you tried adjusting the dust levels?
https://wiki.profittrailer.com/doku.php?id=configuration.properties

**Comment by jokaorgua** [comment]
yeap. no luck.

current dust levels are
BTC_dust = 0.000999
ETH_dust = 0.00999
BNB_dust = 0.0105
USDT_dust = 1.16

**Comment by taniman** [comment]
Please be aware that DUST on binance is calculated baes on the value we recieve from binance that indicates something is dust. So you cannot adjust this value. 

To buy and sell BCCUSDT as in your example minimal value is $10 according to binance.
The bot was showing the value to be $9.97

which is less than required value of $10 so it was put in dust log.
In reality the value was more than $10 because we removed the fees from the value

This is the ONLY reason why you could sell it manually. Because the value was > $10

So the bot is not doing anything wrong here. Dust values  in confguration.proeprties are ignored because Binance tells us what is correct dust value.

**Comment by jokaorgua** [comment]
but it is not taken from dust log back to pairs log when the value is greater than 10$ ?
