### ISSUE TITLE
[BUG] DCA Stop Loss Triggered before completing

### ISSUE THREAD

**Issue by ssbn** [taniman/profit-trailer#1438]
According to the documentation, DCA is only to trigger a stop/loss sale on a coin that has finished executing DCA. [DCA Wiki](https://wiki.profittrailer.com/doku.php?id=dca.properties)

I have coins now that have been sold without any DCA executions at the stop/loss trigger set.

Here's the DCA config:

`buy_strategy = LOWBB`
`buy_value = 10`
`buy_trigger = -2`

`ignore_sell_only_mode = true`

`stop_loss_trigger = -6`

`enabled = true`
`trailing_profit = 1`
`trailing_buy = 1`
`sell_value = 0`
`max_cost = 0.0001`
`max_buy_times = 1`
`sell_strategy = GAIN`
`max_buy_spread = 1`
`sell_trigger = 1`
`min_buy_balance = 0`
`min_buy_balance_percentage = 0`

**Comment by taniman** [comment]
I think you should read the wiki again. 
you have max_cost set at 0.0001

I am not sure what market this is. But a max_cost of 0.0001 whould certainly indicate that DCA is finished.
Because none of your coins can double down anymore. And the wiki says. If the coin cannot double down anymore stoploss will be triggered.

![image](https://user-images.githubusercontent.com/6751341/37365403-b05b8dee-26fd-11e8-94f8-b53ef1fa8ada.png)

**Comment by boaz33** [comment]
I’m sill trying to set it up. It shouldn’t be trading

**Comment by MrS1n1st3r** [comment]
What if 
max_buy_times is NOT reached NOR
max_cost is NOT reached AND
thereIS enough balance to keep using DCA, but the coin pair is UNDER min volume?

Is DCA considered finished?  Does the stop loss execute?
