### ISSUE TITLE
[Feature Request] Trailing Stop Loss for Gain Strategies

### ISSUE THREAD

**Issue by CryptoZenMaster** [taniman/profit-trailer#1457]
_Further to request #988, which may have been misunderstood._

A trailing stop loss feature would allow PT to move a stop loss order up as the price of a coin rises.  This would allow for an additional safety or even a pseudo sell strategy when using HighBB or other strategies that buy rising prices.

This should be safer than only relying on a gain / trailing sell strategy because the stop loss order would already be on the exchange. No risk of having a cancelled order due to timeout, timing or connectivity issues that sometimes prevent a sell order from being submitted.

Setting could be something like All_stop_loss_trailing / XXX_stop_loss_trailing, measured in % to represent the % below the current price that the stop loss should be kept at.

Example with All_stop_loss_trailing set to 2(%):

1. Buys a coin near the start of a rise using HighBB (this would be considered 0%)
2. Places an initial stop loss 2% below the buy price
3. Coin price rises 4% over a period of time
4. Stop loss gets moved up 4% to trail the price rise (now 2% behind the current price)
5. Repeat 3 & 4 if price continues to rise

Other accompanying settings such as All_stop_loss_trailing_wait_time might be helpful to define how often to update / move the stop loss order.

**Comment by CryptoZenMaster** [comment]
In theory this isn't any different than sell trailing, but I think in practice it would be safer.  The existing gain / trailing sell strategies could still be used.  Best of both worlds?

**Comment by taniman** [comment]
I suggest you add this to the enhancement branch as I do not see myself adding this feature as of yet without more people requesting it

**Comment by bvebve** [comment]
I arrived to the same conclusion. A ### trailing stop loss would be a very good complementary selling strategy.
Imagine you expect the price to increase by 10%. What happens when the price stops at 9.9% and goes down abruptly? Yes, your profit is gone.  
What about a stop loss that moves up with your gain? So if your expectations (10%) are frustrated you will not lose all what you already earned.

If this method is so complicated to implement, you could implement a less efective soluction: - Please, allow **positive Stop Loss** !!!
