### ISSUE TITLE
Recently bought coins not showing up in the Pairs Log

### ISSUE THREAD

**Issue by JaySatthee** [taniman/profit-trailer#1475]

**Comment by riserpete** [comment]
..and not in the DCA Log either..

**Comment by YoJeff** [comment]
PT does not have an ExcludedPairs list.

**Comment by riserpete** [comment]
sorry! right..that's from feeder..unrelated then..the initial problem remains though, where some pairs (manually bought or recently purchased) don't show up in any of the Logs.

**Comment by taniman** [comment]
manual bought coins take up to 10 minutes to show up. or may not appear until you restart the bot.  So if that's the case than this is not the issue.

**Comment by riserpete** [comment]
thank you for the response and sorry @JaySatthee for hijacking this thread, where you reported the issue :)
for me, also after restart of the bot, coins that i bought weeks ago, don't show in any of the logs (in addition to the recently purchased ones)

**Comment by taniman** [comment]
please provide your trading folder and log file and also tell me what coin you think is not sohwing up

**Comment by JaySatthee** [comment]
I fixed it. Had some spelling mistakes in the pairs log..

**Comment by riserpete** [comment]
@taniman not working on my side unfortunately, i'll add the requested information here: the bot bought NEO, it doesn't show in pairs, also not in DCA and not in the other logs since he didn't sell it yet, but it's in my binance portfolio
[trading.zip](https://github.com/taniman/profit-trailer/files/1841355/trading.zip)

[ProfitTrailer.log.zip](https://github.com/taniman/profit-trailer/files/1841356/ProfitTrailer.log.zip)
![screen shot 2018-03-23 at 12 39 35](https://user-images.githubusercontent.com/26596353/37827373-7e62eafc-2e97-11e8-8d52-3e072dd325a6.png)
