### ISSUE TITLE
Web interface stops working

### ISSUE THREAD

**Issue by yeahman2018** [taniman/profit-trailer#1511]
Every day web interface stops working. Ubuntu 17.10, latest versions of security, java and PT. Requires restart of PT, fixes problem every time.

**Comment by GuillerVks** [comment]
Please, Attach log.

**Comment by yeahman2018** [comment]
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1855780/ProfitTrailer.log)

**Comment by yeahman2018** [comment]
Thanks, ok. I'm unsure how to fix it. PT is working, notifications work, pm2 log works, just web interface stops.

**Comment by taniman** [comment]
web interface stops working is not something I can do anything with. I am not even sure what you mean with this. 
please explain more.

How do you know that the web interface is not working?

**Comment by yeahman2018** [comment]
What I mean is that profit trailer is not sending anything to the web. PT is working but I can't use the web browser to see anything. Error on browser is 'cannot connect to server', but it gets fixed when I stop and restart PT. It's not my ISP because it happens on multiple networks. Could be VPS but rebooting PT fixes it. Could it be java? I reinstalled java too. Latest versions of every package.

**Comment by knowngate** [comment]
im too facing ,issue with web interface. i m not able to see anything on my browser but on terminal it show that bot is running. i m using ubuntu 16. lts ubuntu.

**Comment by Printersmith** [comment]
These VPS are total garbage.  I have to reboot mine every day or three.  They aren't real servers and the stupid people hosting them just shut them off so they can save money, I'm not sure what is going on.  But I had to send at least 20 emails to VIRMACH to get the damn thing to stay online for 24 hours at once.  Also when you reboot the server, it doesn't go to the desktop.  Rebooting or crashing REQUIRES you to RDP into the thing to get to the desktop or the bots won't start.  So having your bots in Startup is a complete waste of time because the server doesn't "actually start" after a reboot, it just goes into sleep preboot mode where nothing is happening.  VPS SUCKS!!!!!

**Comment by taniman** [comment]
@yeahman2018 .  when this happens I advice you to contact someone from support so they can have a look with you. Maybe that way someone can figure the problem.
