### ISSUE TITLE
ERROR ProfitTrailerService - chartData - Binance does not support this period

### ISSUE THREAD

**Issue by mashuble** [taniman/profit-trailer#1517]
My ProfitTrailer bot seems to write this error every second in my log file. I'm on 1.2.6.25.

`ERROR ProfitTrailerService - chartData - Binance does not support this period`

**Comment by twig123** [comment]
Github isn't the place for support questions. Please join the discord channel for support questions.

However, your issue is that you have an invalid period specified in your indicators.properties file. The wiki here lists which periods are supported:
https://wiki.profittrailer.com/doku.php?id=exchanges#binance
