### ISSUE TITLE
V2 setting files being upload to PT Trailer servers or local?  

### ISSUE THREAD

**Issue by Skippydog** [taniman/profit-trailer#1569]
> 6. Once all files are configured to your satisfaction ensure the three trading files are inside the ProfitTrailer V2/initialization folder. On first boot-up these files will be read by the bot, uploaded to the PT servers and encrypted for storage locally or on our servers according to your settings.

This section is a bit confusing.  How come you are requiring the settings files to be uploaded to your servers?  Or am I misreading this and the data will stay local to the box?  It says according to your settings but I am going through the wiki and I don't see an option to change it.

**Comment by taniman** [comment]
in application.properties there is the option
disable_online_config = true

if you use that the following will happen.
1. we encrypt the settings like always
2. we send the data to our servers
3. we encrypt the data again with some extra information
4. we send the double encrypted data back to you
5. the data is stored on your machine

why do we send to our server? Because that's how our new logic works
