### ISSUE TITLE
Telegram saying “Ticker Update: something is wrong with your bot, please restart” 

### ISSUE THREAD

**Issue by iAmVaeVictus** [taniman/profit-trailer#1576]
Running bot v2 on Polo and Bittrex. Getting this message every 20 seconds for each bot. Over and over. 11,000 per day. 

Mac OSX high Sierra. Terminal app (not PM2). 36 GB RAM.

**Comment by statik121** [comment]
I have the exact same issue. Clean install of PTv2 on brand new VPS instance of Windows 2016 Server and Bittrex. I use Telegram and had about 1,200 messages when I woke up this morning. The message does not show up in my terminal window but I keep getting random JAVA errors and when asking for clarification on PT Discord #support I was told to ignore it. It’s kind of hard to ignore. Otherwise, the bot seems to be running and making buys and sells.

**Comment by XxxSpiritvsxxX** [comment]
Same here.

**Comment by koeleman** [comment]
same here, old profit trailer gave a nonce error on polo, new PT2 doesn't give a clear error message. Switching back to old version till it is fixed. This is not working unfortunately.

**Comment by YoJeff** [comment]
Dup, consolidate #1594
