### ISSUE TITLE
[QUESTION] Will you bring back Total Pending Value (TPV)?

### ISSUE THREAD

**Issue by sannyd** [taniman/profit-trailer#1662]
It's important for my accounting rather than assuming I've taken a loss if I've bagged up?

**Comment by empbac** [comment]
But the exchange doesn't have that data. The bot knows it though because it keeps track of where it buys and sells and DCA's, so the data is all there already to suggest, 'here is the amount you will have if you sell all bags at minimum profit.' I got used to looking at this, and could get a quick idea of how well or how poor the trading was going. Not used to not seeing it, kind of miss it. I wonder why it was removed.

**Comment by sannyd** [comment]
I of course, agree with @empbac because the TPV meant so much to me it's stopping me from using v2.0 since buying is not important to me with the current state of ALTS.  

However, I understand what @SgtBatten is saying because the exchange has the actual numbers and trade information so we should be able to keep track. 

My new question is, was it really that bad to keep it?  It was a feature that was being used, at least by myself and @empbac, so, why take it away?

**Comment by YoJeff** [comment]
Toss it over in the features github, since it's now a feature request.   Who knows, maybe it will get enough traction to make it back in.   https://github.com/taniman/profit-trailer-enhancements/issues

**Comment by sannyd** [comment]
Thanks @yojeff. 

@empbac, https://github.com/taniman/profit-trailer-enhancements/issues/277 
Hopefully we can get it back in.
