### ISSUE TITLE
(BUG) Panic Sell in one bot works in all bots with the same license

### ISSUE THREAD

**Issue by pheonix727** [taniman/profit-trailer#1696]
i have to binance bots with the same license key
am running them both on testmode

when i activate panic sell in one bot, the other bot also does panic sell

**Comment by SgtBatten** [comment]
This is most likely because you did not choose a unique settings name when you first ran the bot.

You should be able to use the swagger API to delete the config from one bot and then restart it to reinitialize it.

https://wiki.profittrailer.com/doku.php?id=swagger_api

I will reopen this if you prove otherwise but come to discord for support if you need it.
