### ISSUE TITLE
Can I switch to another exchange untill the issue with Bittrex is fix?

### ISSUE THREAD

**Issue by kj3407** [taniman/profit-trailer#1717]
Can I switch exchanges, I have not bee able to use V2 at all on Bittrex and since they have been trying to throttle Bots api, i having the same issue, not as bad, on V1 also.  I did try to do this but stoped when I saw on discort, my lic# is called a Bittrex bot. So I wonder if i can even switch at all or do I have to buy another bot alltogether?  I only want to trade on one exchange at a time so I have no need for two bots, I like Bittrex more than Binance but since I can't use Bittrex I wanted to switch until the issue is fix, is this possible? and can I switch back later?

**Comment by GeckoTrader** [comment]
I'm in the same situation,would be great to be able to switch exchanges. It's becoming very difficult to trade through Bittrex

**Comment by gbrottman** [comment]
Having the same problem. I upgraded feeder and so far it’s not accumulating errors and crapping out. However PT V1 is now spitting out lots of error messages. Going to upgrade to PT V2 next.
Do you think it’s possible that Bittrex is pushing back from the increase in PT Bot traffic.

**Comment by emx0r** [comment]
Same problem, the PT is no unusable on Bittrex. I'd like to switch to Binance

**Comment by B0mBeur** [comment]
way too much error with bittrex there is tons of error in the console. I'm tempted to switch too

**Comment by BOBALLEX** [comment]
I fully support you

**Comment by kingokeke** [comment]
I also believe that the exchange should be able to be switched since license validation happens on PT servers. Its something that should be built into the PT assistant.

**Comment by NOP-Commander** [comment]
Hi all,

just for the record: I'm running a v1 bot on bittrex and encounter throttling issues. Sometimes I see an incorrect balance but trading still works. I can't see/feel an impact on the trading performance on my side so far compared to my Binance and Poloniex bots. I know this doesn't make things better for those who encounter heavy impact on their Bittrex trading but it's kinda weird (at least for me) to see the spread in impact caused by api issues of Bittrex.

In Bittrex' blog I saw the announcement for beta website and beta api by end of march. Is that a realistic temporal forerun for devs to implement a new api anyway? From what I feel the new api incorporates many changes to the code.

Just my 2 nops.

**Comment by kj3407** [comment]
@taniman I have created several tickets, all I get is that you guys are working on it, 3 weeks ago, so that's been done.
