### ISSUE TITLE
PT 2.0 loads different default config

### ISSUE THREAD

**Issue by radawson** [taniman/profit-trailer#1737]
For some reason, whenever PT loads the Default config, it pulls an older configuration. Is there a way to permanently change the default config?

**Comment by SgtBatten** [comment]
It should be loading the config you last saved.

Please use the swagger API (see the sidebar of the wiki) to list and then delete all your configs. Then reinitialize with the files in the Initialization folder.

**Comment by riggermortum** [comment]
I had the same issue, my own fault for not reading the wiki!  There were  a lot of changes in v2, and I didnt know about the new feature that saves your config online.  I was swapping/changing the properties files, and each time I loaded, it went back to the old one.  Ive since gone offline, deleted the offlinedata file, but had to stay offline, as trying to reconnect restores previous config.  Despite following the instructions ion the Wiki>Common Errors page, I cant fix it, so have stayed offline.  

Someone on discord mentioned that using swagger could lose historical logs, is this correct?

**Comment by taniman** [comment]
@riggermortum I do not see why using the api can lose your historical logs. As it only reads log data.
