### ISSUE TITLE
PT2.0 high CPU resource useage

### ISSUE THREAD

**Issue by jojobobgg** [taniman/profit-trailer#1794]
PT 1.X is very fast and lower CPU usage, but PT 2.0 very slow, seeing high CPU usage.
![wx20180506-090242](https://user-images.githubusercontent.com/38686781/39668839-5264b2fe-510c-11e8-8f5c-bfd89560a60a.png)

**Comment by cupid-stunt** [comment]
Wow, are you mining? I'm running two bots on a Pi and my CPU is nowhere near that.

**Comment by jojobobgg** [comment]
@cupid-stunt I am not mining , just a vps for install the profittrailer .

**Comment by NOP-Commander** [comment]
Hi @jojobobgg,

which process(es) cause high CPU-usage? Please check the tab "processes", click the button labeled "show processes from all users" and report back and/or provide a screenshot. Maybe additional screenshots from "Resource Monitor" will help identifying possible bottlenecks/reasons. Yet i see no proof that Profit Trailer is responsible for the high CPU-usage. Someone with more deep insights in identifying performance bottlenecks on Windows might assist in this issue since I'm more a Linux-Joe and my Windows Kung Fu is limited.

**Comment by taniman** [comment]
Please contact support maybe someone can help with investigation.
