### ISSUE TITLE
Issue with 2 Instances of PofitTrailer on two different Binance accounts

### ISSUE THREAD

**Issue by lorddr** [taniman/profit-trailer#1815]
hello, I have a problem with ProfitTrailer. I have two instances installed on a VPS both on separate binance accounts. One is on BTC and the other on ETH. The issue is that when I start the second one (ETH one), the Instance that I have on BTC imports the Pairs and DCA configs from the ETH. And after that any change that I make on any one of the instances on the DCA file or the PAIRS file gets imported in the other one.
why is that happening?

**Comment by SgtBatten** [comment]
its happening because you used the same config name for each bot or are using the same api keys (but probably not as you say different accounts)

the workaround here will get you back to the naming screen and allow you to reinitialize the config with a unique name: https://wiki.profittrailer.com/doku.php?id=common_errors#unable_to_retrieve_latest_settings_null
