### ISSUE TITLE
STOCHRSI Still in 2.0.5 - BINANCE

### ISSUE THREAD

**Issue by samick123** [taniman/profit-trailer#1876]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.5

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Operating System:
- [ ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [x] Mac OS

## Expected Behavior
STOCHRSI in Pairs and Possible buy should reflect the values shown in Binance when all parameters are within exchange requirements.

## Current Behavior
In making an attempt to implement STOCHRSI, the values are rarely correct. RSI iscorrect, however, STOCH seems to not report correctly from the exchange.

## Troubleshooting
Double checked exchange requirements for the indicator, confirmed settings with support.

## Possible Solution
Separate coding and calculations for STOCH, RSI and STOCHRSI

## Steps to Reproduce

1. Monitor values for STOCHRSI and reference Binance
2. Monitor values for RSI and reference Binance 
3. Monitor values for STOCH and reference Binance
4.

## Configuration
[https://pastebin.com/aaj9pxs8](url)
## Log files/console output
Nothing irregular in log, no errors.

**Comment by SgtBatten** [comment]
but the template :(

**Comment by taniman** [comment]
I think you are mistaken as to how PT STOCHRSI works. 
Currently it will not match Binance nor TradingView as our stock RSI is not using the K and D oscillators

This it's not a bug. And is working as intended.

Due to this confusion though I will amend the stochRSI logic to reflect the exchanges better in the upcoming minor release. in about 1 week or so
