### ISSUE TITLE
REBUY TIMEOUT set in DCA also prevents buying a coin in Possible buy after it was sold from DCA

### ISSUE THREAD

**Issue by Mikeeetrue** [taniman/profit-trailer#1890]
## ProfitTrailer info
Version: 2.0.7 (this issue wasn't sold since 1.2.6)
Exchange:
- [x] Binance
Market:
- [x] BTC
Operating System:
- [x] Ubuntu (please specify version)

## Expected Behavior
After the coin is sold from DCA then REBUY TIMEOUT set in DCA is reset.
## Current Behavior
After coin is sold from DCA with REBUY TIMEOUT it appears in Possible Buy with REBUY TIMEOUT
## Troubleshooting
Have no idea how to fix
## Possible Solution
Add the parameter to DCA:
DEFAULT_DCA_rebuy_timeout_sell_reset = true
which will turn on reseting the counter after the coin was sold

## Steps to Reproduce
1. Set DEFAULT_DCA_rebuy_timeout = 10 in DCA
2. Do DCA for the coin
3. Sell the coin
4. Check possible buy log

## Configuration
https://pastebin.com/X0z6XFJN

## Log files/console output
https://gyazo.com/11cd2460c7ccf64eae778fa2b99723d9

**Comment by taniman** [comment]
That is not an issue. but how the functionality works.  
As people do not want the bot to buy too quickly even after it just sold to not buy into a possible bag.

Adding a new property means adding new features. So that is not meant to be asked here.
I recommend you add your request to the enhancements project
