### ISSUE TITLE
Still occasional wrong buy price on new buys (2.0.7)

### ISSUE THREAD

**Issue by alexdolli** [taniman/profit-trailer#1891]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.7

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [x] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
My ETH PT just bought EOS and it was up over 6% immediately. Checked the bought price with the exchange and it was wrong. Luckily I could reset the bought price via HotConfig before it sold for a fake gain (loss).
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2022165/ProfitTrailer.log)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
Can you provide your profittrailerdata.json?

**Comment by alexdolli** [comment]
Here ya go...
[ProfitTrailerData.json.txt](https://github.com/taniman/profit-trailer/files/2023851/ProfitTrailerData.json.txt)

**Comment by taniman** [comment]
@alexdolli  I have gone over your complete log. Looked at this very close.  And the problem in your case occured because for some reason the data we needed was not present in the bot. According to you ProfitTrailerData.json

So could you hand me the complete log file as now you have copied only a bit. Upload it in a zip here or give to someone from support. 
Thank you

**Comment by alexdolli** [comment]
[ProfitTrailer.zip](https://github.com/taniman/profit-trailer/files/2033117/ProfitTrailer.zip)

**Comment by taniman** [comment]
2.0.11 has a possible fix
