### ISSUE TITLE
Error while refreshing data from profit trailer.

### ISSUE THREAD

**Issue by mfactor50** [taniman/profit-trailer#1915]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.01

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Current Behavior
Always says there was an error refreshing data from profit trailer.

## Troubleshooting
Restarted bot, change monitor port.

## Possible Solution

It say to check connection. If connection is fine, have a pint and it should correct itself.  Now I'm drunk and not sure where to look.  No errors in log file. I've changed monitor port. restarted bot, I'm running PTMagic. It seems to be running and functioning fine.  

## Steps to Reproduce

1.  
2.
3.
4.

## Log files/console output
 .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.9.RELEASE)

2018-06-04 11:00:33 INFO Application - PT Version: 2.0.1
2018-06-04 11:00:34 INFO Application - Java Version: 1.8.0_161
2018-06-04 11:00:44 INFO ProfitTrailerService - PAIRS Heartbeat
2018-06-04 11:00:44 INFO ProfitTrailerService - DCA Heartbeat
2018-06-04 11:00:44 INFO ProfitTrailerService - Cache Heartbeat
2018-06-04 11:10:47 INFO ProfitTrailerService - Cache Heartbeat
2018-06-04 11:10:47 INFO ProfitTrailerService - DCA Heartbeat
2018-06-04 11:10:48 INFO ProfitTrailerService - PAIRS Heartbeat

**Comment by coinman777** [comment]
I am having the exact same problem, any thoughts? I have reinstalled PT, rebooted, restarted internet, nothing seems to change the situation.

**Comment by SgtBatten** [comment]
You need to update. Currency API used in older versions got turned off by the provider.

**Comment by Roxxiga** [comment]
Upgrading to the newest version of the .jar fixed it for me.  It's weird though because my eth bot was working fine before updating but the btc one wasn't.  Thanks for letting us know the fix, SgtBatten.

**Comment by mfactor50** [comment]
Fixed it for me also. Thanks!

**Comment by yesacrenots** [comment]
I seem to have same problem. What do I need to update??

**Comment by SgtBatten** [comment]
your bot

**Comment by yesacrenots** [comment]
Where do I go to Update?  Little confused.

**Comment by SgtBatten** [comment]
https://wiki.profittrailer.com/doku.php?id=upgrade_instructions

this should get you updated

**Comment by bartgrefte** [comment]
I just got this problem with v2.0.16 on W7x64. the log didn't indicate any problems, the heartbeat-messages kept on coming but the webinterface wouldn't load any data anymore and gave the same error as reported in this topic.

A restart did fix it though, but since this shouldn't be happening I thought I'd report it here.

**Comment by TonyG99** [comment]
I'm having this same issue when I transfer my ProfitTrailer instance from an AWS t2micro instance to my local computer -- everything works on AWS (albeit very slowly, due to insufficient memory), but when I stop the bot on AWS, copy the entire folder to my laptop and restart, I get the dreaded:

"There was an error while refreshing the data from ProfitTrailer. Please check your connection. If your connection is fine refresh the page and have a pint."

It also seems to be confused about the monitor password -- even though I successfully used the monitor password to log in.

Well, I've had three pints now, and my Internet connection is fine, but it's still not loading the monitor data!

I'm running ProfitTrailer 2.2.12 (the current version at time of writing).

![2019-03-23-profittrailer-issue](https://user-images.githubusercontent.com/25991228/54872776-3cb34b00-4da0-11e9-8bd9-344548f9123f.png)

**Comment by SgtBatten** [comment]
You'll get a better response from discord support. Chances are your firewall or something like that (adblockers even) is blocking your bot. Try another browser or try it in incognito mode
