### ISSUE TITLE
Having issues with forgetting price after upgrading to v2.0.12. 

### ISSUE THREAD

**Issue by sachah** [taniman/profit-trailer#1938]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: v2.0.12

 
Exchange:
- [ ] Bittrex
- [ x] Binance
- [ ] Poloniex

 
Market:
- [x ] BTC
- [x ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ x] Windows (please specify version) Windows Server 2016 Latest
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

Should not forgot prices. 

## Current Behavior

It just started to happen after upgrading to v2.0.12. Did was not an issue with previous releases. It is also not being solved by hotconfig fixes. It forgets about the price afterwards. Having problem with LTC and BNB. 

## Troubleshooting

Restarted the server. Changed price by hotconfig setting. 

## Steps to Reproduce

1.
2.
3.
4.

## Log files/console output

 

[ETH - Profit Trailer.log](https://github.com/taniman/profit-trailer/files/2091740/ETH.-.Profit.Trailer.log)
[BTC -ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2091741/BTC.-ProfitTrailer.log)

**Comment by SgtBatten** [comment]
For BNB this is expected behaviour. So don't focus on that. We will just focus on LTC.

**Comment by sachah** [comment]
Ok, but never had issue with BNB before upgrading to v2.0.12. I downgraded to v2.0.10 now and the problem went away for BNB and LTC.

**Comment by taniman** [comment]
First of all I would like to mention that 2.0.10 average calculator is buggy and over optimistic in its price calculation.

I went over log log file and below my findings

At the moment of your your you owned *0.934* sellable LTC 
The bot normally tries to find the closest match possible.

But while traversing your whole tradehistory of LTC we found the following
![image](https://user-images.githubusercontent.com/6751341/41374160-b263403a-6f52-11e8-917e-72d3773fc46b.png)

We count all your buys up to the point of the selected price (2018-04-07 19:46:31) in the image above.
The total amount of LTC bought up until that point is 0.916
If the go to the next point below and count everything we get 0.982

So first point was too little. A difference of 1.92% with what you currently own
Second point was too much already. A difference of 4.88% with what you own.

Not that at this point there has been no sales. So it's not possible for this balance to not match.
So average calculator with continue to try. But in the end the price still cannot be calculated.

So even though 2.0.10 shows you a price. According to my manual logic it's 2.0.12 that is ding the correct thing as there is too high of a price discrepancy with actual trades made. 

So it's either commissions you are receiving or coins have been sent to pending or withdrawn. In any case outside influence is causing a mismatch in coin amount and thus we cannot calculate

My suggestion is to set the correct bought_price and the bot will use that going forwards.

And for BNB. It is indeed so as you continue paying fees with BNB the price will continue to get lost due to same logic described above

**Comment by sachah** [comment]
Hi.

Thanks for the reply. Two points below. No solution for BNB, it will also have an issue because I am paying commission fees with BNB?

1. You are correct that I used some LTC to pay for a service. 
2. I tried to do a hotconfig with bought_price but it didn’t keep it and kept giving the issue. Any suggestions to resolve?

Sacha
