### ISSUE TITLE
Profit percentage and fees

### ISSUE THREAD

**Issue by DevilSquare** [taniman/profit-trailer#1959]
THis is basic question that discord support was not able to help with. 
![capture](https://user-images.githubusercontent.com/19258637/42121724-cee63aa6-7bf9-11e8-802f-2321411f2779.JPG)

https://ibb.co/b3ReMd

buy price = 14.79  .. highest bid price = 14.69 ... gross profit at this instant( fees + pure profit ) = -0.1/14.79 = 0.0067 = - 0.67% ...    P% is shows - 0.88% ...  thus fees =  -0.88% -(-0.67%) =  -0.21%

Where am i calculating wrong? The fee should be max 0.1%.. 

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2151440/ProfitTrailer.log)

NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.0.13

 
Exchange:
- [ ] Bittrex
- [ x] Binance
- [ ] Poloniex

 
Market:
- [ ] BTC
- [ ] ETH
- [x ] USDT
- [ x] BNB
- [ ] XMR

 
Operating System:
- [ x] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

The fees should be 0.1%. But it calulates out to be ~0.2%. 

## Current Behavior

Every sell

## Steps to Reproduce

1.
2.
3.
4.

**Comment by taniman** [comment]
Hello A couple of questions.

Who from support did you ask that could not help you with this. As I guess they need some more help.

Seconds are you using BNB for fees? So that I can give you a better answer.

**Comment by DevilSquare** [comment]
yes , i have set the settings to pay fees in bnb ... n yes it is getting deducted in bnb too .. i checked on binance... 

Kyrose was helping me out there.

**Comment by taniman** [comment]
Its a simple answer.

0.1% when you buy
0.1% when you sell.
So your profit is always 0.2% lower than actual.
Even if you use BNB (which halves this fee) we calculate this static fee of 0.2%

Why static? Because if you run out of BNB you will get a combined fee logic. And this only complicates the bot logic.

**Comment by taniman** [comment]
No there is no way of doing this. 
And I do not feel it should be there. Cause if you set it incorrectly you will sell with a loss

**Comment by DevilSquare** [comment]
Thanks. But everytime I buy the effective buy price is also set substracting the fee, isnt it? Then if I sell and count the fee again while I m selling it , am I not counting it twice?

**Comment by taniman** [comment]
We do not use a fee on buy. Only on sell. 
So if you used BNB to pay for the fee we assume you paid 0.1 fee for that buy.
So in order to sell with a profit you would need to cover the 0.1% fee plus cover 0.1% selling fee.

That's the default fee you would pay on binance if you were not using BNB to pay the fees.

0.1 buy + 0.1 sell = 0.2 total fees.

If you beleive this is not correct please provide your calculations

**Comment by DevilSquare** [comment]
This is matching with my calculations. Thank you for the explanation.
