### ISSUE TITLE
Feature Request: BTC reserves specifically for DCA

### ISSUE THREAD

**Issue by Concept211** [taniman/profit-trailer#198]
I find that currently, PT continues to open as many trades as possible until the BTC funds run out. However, it leaves the old trades that are still underwater without any available funds to cost average them down as prices get lower. It would be great to allocate a specified amount of BTC just for this use and NOT to be used to open new trades/coins.

**Comment by taniman** [comment]
this is already implemented.
ALL_min_buy_balance.
The bot will try and maintain a balance. So it will only trade with the balance above this.
if you have 0.5 BTC in your account
you specify ALL_min_buy_balance = 0.3

the bot will only buy new trades with 0.2BTC

So you know DCA always has at least 0.3BTC to play with. because by default this min_buy_balance in dca is 0
