### ISSUE TITLE
BUG: Ethereum showing as 0.0%

### ISSUE THREAD

**Issue by TedHoryczun** [taniman/profit-trailer#2040]
When you have Ethereum, it shows in the pairs tab. It shows as 0.0%. Only happens when you transfer money to Ethereum. 

## ProfitTrailer info
Version: 2.1.5

Exchange:
- [x ] Bittrex
- [ ] Binance
- [ ] Poloniex

Market:
- [x ] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [x ] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior
Shouldn't be shown anywhere in gui

## Current Behavior
Ethereum showing in gui even though it's a wallet, not a trading coin. 

## Possible Solution
Logic:
Boolean isCoinAWalletCoin;
if(isCoinAWalletCoin){
//Don't show in pairs
}else{
//Show in pairs
}

## Steps to Reproduce
1. Put money into Ethereum
2. See Ethereum in pairs tab

**Comment by jadiesel** [comment]
When you transfer a coin into your exchange account, it will show up in the bot's monitor, and start asking for a bought price. This is by design. If you do not want to trade that coin, you need to disable trading for that coin.

ETH_trading_enabled = false

You should also consider using an exchange account just for the bot, and use a second account for manual trading.  And never hodl long term at an exchange.

**Comment by SgtBatten** [comment]
As mentioned above. The bot can see ANY coin in your account that you let it see. This is not a bug, you have complete control over this.
