### ISSUE TITLE
Buy Strategy: Only buy if 24hr change is greater than X%

### ISSUE THREAD

**Issue by Concept211** [taniman/profit-trailer#205]
Simply look at the 24hr % change which is already available for each coin in the Possible Buy Log. This way, you're not buying into a coin that's on a downtrend and reduce the risk of creating a DCA "bag".

A simple configuration option to decide to trigger your Buy strategy only if that coin is above X% change. This would be useful as not a standalone strategy, but an _additional_ one to be used when the **multiple/combination strategies feature** becomes available.

**Comment by CryptoInvestment** [comment]
This was also a feature that I was thinking about after that @taniman I think explained me that the bot don't read the long past of the ticket to not buy token that are on along fall trend.

**Comment by CryptoInvestment** [comment]
And I think 24H based clue can give us good opportunities than the long term (but a little risky for the long fall trends)

**Comment by nocturnal86** [comment]
Useful one idea. The values in this strategy are better to be in range like: 5-15

So the bot will look at coins in the range of 5 to 15% and not above that 15% also.

Because if we have only 5 and the bot picks a coin at 25% uptrend, those ones are dangerous too for creating heavy bags

**Comment by Davethegithub** [comment]
Yeh nocturnal86, agreed. 

 I've had the same thoughts on this problem is 24hr % change is not necessarily correct indicator of overall trajectory either.  A coin on 3 month loosing streak thats an obvious bad bet could have a small pump and have a positive 24hr value.  The inverse os also true and lock you out of a good buy.  

Using a long smooth curve SMA and taking the last 24hrs might smooth this out.  

I also was considering a scenario where if 2 out of 3 are true then OK to trade.  So you have 3 periods -  just for example -  1 month 1 week 24hrs.  PT looks for a vol increase of between min +x% & max +y% in any 2 before a coin can be traded.

**Comment by ulearn** [comment]
Yes. This would be a tremendous asset to the bot. The ability to track a coins 24Hr history would change the game - a low bb setting in a 24hr bull trend would be a safe setting to buy from. Seems like this data is already being pulled in(?). Be great if it could be used! :)

**Comment by taniman** [comment]
see #219 dev info
