### ISSUE TITLE
Wrong Calculation in €

### ISSUE THREAD

**Issue by xyr0x** [taniman/profit-trailer#2055]
## ProfitTrailer info
Version: 2.19

Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

Operating System:
- [ 2k16] Windows (please specify version)
- [ ] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Current Behavior
The ads for the exchange rate in € are different for PC and smartphone.
At Current Value or Startbalance I have different information on both devices.
e.g.
Starting Balance PC: EUR Estimated Value 12,257.00
Start Balance Smartphone: EUR Estimated Value 12,244.12

I have the difference in the start balance, current value, profit in the sales log etc.

I emptied the cache on both devices. On the smartphone I have additionally deleted the entire device cache. The time zones are identical on all devices including VPS.

Both without success. The values remain different.
The moderator "PondScum [Support]" had no direct explanation and asked me to open the ticket.

Many Thanks.

## Troubleshooting
- Check the Timezone
- Delete the Cache
- Wipe whole Device Cache
- Restart Bot

## Possible Solution
nothing

**Comment by djcrypto75** [comment]
So lets say you start up PC bot at 1200 at Mobile bot at 1201. The prices will be different. 
We check the Euro against the BTCUSD price and calculate with that.
Also they do not call the APIs at the same time. To have exactly the same prices they need to be synchronized at exactly the same ms.

**Comment by SgtBatten** [comment]
@djcrypto75 does that apply to the same bot?

I believe this user is looking at the same bot. So the prices are stored locally on the browser?

**Comment by taniman** [comment]
the euro/dollar prices come from an external api and is done in the frontend.
yes @SgtBatten the price is stored locally for x minutes to prevent limitation with this external API

Due to the fact that we are not allowed to call this external API too many times we cache the data they give us in our browser. 
And every x minutes we update this data 

So as @djcrypto75  said above. If both browsers are not opened at the same time the prices will not match. 
But it's not only opening at same time. Both browser need to have the last cache time at same time too. 

In order to understand this. Try opening 2 incognito windows
1 on your laptop and 1 on mobile at the same time

When opening incognito windows there is no existing cache so we are retrieving latest data from the currency API and the values will match

**Comment by djcrypto75** [comment]
Also, all currencies are calculated against the BTCUSD price on your excchange and this is also a moving price and the frontend calls the backend each 5 seconds from when you start it up. 
So to make everything match all prices you need to start the frontend/GUI at the same second.
