### ISSUE TITLE
NullPointerException Binance v2.1.23

### ISSUE THREAD

**Issue by des1re10** [taniman/profit-trailer#2111]
Since when are NullPointerExceptions Network Connection Errors?

Thats why im asking here, because I havent tried to simply restart the bot yet to solve this simple error.

![48307188-fb847200-e547-11e8-8864-3a3ea29d55b4](https://user-images.githubusercontent.com/11975743/48307843-11992f00-e556-11e8-8a2f-b0257b41058d.png)

**Comment by taniman** [comment]
Please don't abuse the bug system. This is not a support ticket system.

You are receving an error because your binance api is not returning the data the bot is expecting. 
As I previously said. this is a connection issue and a restart might help the problem. But it's not a bug. 
If the bot were to not give you this error you would be seeing 0 data in your bot as there was no data returned by binance.
