### ISSUE TITLE
Make DCA config pair specific (as in pairs config)

### ISSUE THREAD

**Issue by Helmi** [taniman/profit-trailer#222]
It would be awesome to have DCA config using the same structure then pairs.properties so we would be able to change for pairs optionally.

so instead of

```
enabled = true
max_cost = 0.2
max_buy_times = 0
```

make it 

```
ALL_enabled = true
ALL_max_cost = 0.2
ALL_max_buy_times = 0
```

for global config or for example

```
BTC-BCC_enabled = true
BTC-BCC_max_cost = 0.2
BTC-BCC_max_buy_times = 0
```

for a pair specific config

**Comment by smportis** [comment]
Stop loss only works for a specific coin override in Pairs. DCA is a flat stop loss setting for all. 

I believe that this should be changed. 

Suggestion would be to add a DCA coin specific stop loss, or a flag in the Pairs area to set per coin that would “follow” it into the DCA area. 

Pairs file:
BTC-ETH_stop_loss_trigger= -15 
// Below is a new flag - Tells bot to honor the stop loss, even during DCA 
BTC-ETH_stop_loss_DCA= true 

Or DCA File:
// Below is a new setting - Tells bot to stop loss during DCA 
BTC-ETH_stop_loss_trigger= -15

I guess the latter would be cleaner for the end user to remember that is affecting his or her DCA settings. 

If the stop was lower or in the middle of, say, the Anderson DCA limits, it would simply sell when the limit was reached. 

I’m not saying this is the biggest issue out there but to me it’s a medium to high that’s cost me 2x now. Others can comment on their opinions. If seen as valid I’ll add a github entry.

**Comment by japsen** [comment]
I noticed that this ticket is scheduled for version 1.2.7. Just to clarify, will it be implemented to make for _all_ DCA options pair specific? It would be awesome if it's possible to make variations in Anderson buy triggers and to the sell settings.

**Comment by orangebutblue** [comment]
my original issue is already linked, however, I'm going to paste it in here as well:

I wanted to ask for even more coin-specific settings in future versions. Namely, being able to set trailing_profit for each coin, instead of having a general value for all coins,
Some coins are generally more unstable than others, and therefore require bigger trailing-values.

(this setting applies both to DCA and PAIRS)

**Comment by YoJeff** [comment]
The pairs part of your request is already in place.   The DCA portion is this issue.

**Comment by orangebutblue** [comment]
correct me if I'm wrong, but I don't think the trailing_profit.setting in PAIRS applies to coin-specific pairs, 
i.e.:

ETHBTC_trailing_profit = 0.5

**Comment by smoochy** [comment]
I hope I am right in this thread with my idea.

I would be happy about coin-specific DCA buy triggers.

Meaning, instead of 

```
buy_trigger_1 = -3
buy_trigger_2 = -5
buy_trigger_3 = -7
buy_trigger_4 = -10
buy_trigger_5 = -15
buy_trigger_6 = -22
buy_trigger_7 = -35
```

There would be a general:

```
ALL_buy_trigger_1 = -3
ALL_buy_trigger_2 = -5
ALL_buy_trigger_3 = -7
ALL_buy_trigger_4 = -10
ALL_buy_trigger_5 = -15
ALL_buy_trigger_6 = -22
ALL_buy_trigger_7 = -35
```

This could then be altered to (I am on Binance and using their naming):

```
ADABTC_buy_trigger_1 = -5
ADABTC_buy_trigger_2 = -5
ADABTC_buy_trigger_3 = -7
ADABTC_buy_trigger_4 = -10
ADABTC_buy_trigger_5 = -15
ADABTC_buy_trigger_6 = -22
ADABTC_buy_trigger_7 = -35
```

```
CDTBTC_buy_trigger_1 = -2
CDTBTC_buy_trigger_2 = -3
CDTBTC_buy_trigger_3 = -6
CDTBTC_buy_trigger_4 = -9
CDTBTC_buy_trigger_5 = -12
CDTBTC_buy_trigger_6 = -17
CDTBTC_buy_trigger_7 = -22
```

Reason behind this request:

As each coin is dropping on an individual basis, it does not make sense to have a general rule for DCA buy triggers.
If a coin is dropping only a little bit, before it rises again, I want to have low and not so wide spread DCA buy triggers.

Example: 

```
ADXBTC_buy_trigger_1 = -1.5
ADXBTC_buy_trigger_2 = -2
ADXBTC_buy_trigger_3 = -2.5
ADXBTC_buy_trigger_4 = -4
ADXBTC_buy_trigger_5 = -5
ADXBTC_buy_trigger_6 = -6
ADXBTC_buy_trigger_7 = -7
```

If a coin is dropping deep, I need to have wider spreads of DCA buy triggers.

Example: 

```
APPCBTC_buy_trigger_1 = -3
APPCBTC_buy_trigger_2 = -7
APPCBTC_buy_trigger_3 = -10
APPCBTC_buy_trigger_4 = -12
APPCBTC_buy_trigger_5 = -15
APPCBTC_buy_trigger_6 = -20
APPCBTC_buy_trigger_7 = -25
```

I hope this makes sense.

More background info: If this feature is implemented into PT, a request to the PTFeeder team, to dynamically adopt it to certain conditions like the PTFeeder condition `PriceTrendChange` or `LongerTermPriceChange` will make this even more powerful.

**Comment by Fransenson** [comment]
I second this. Great suggestion!

**Comment by luisjotapepe** [comment]
Great feature! was just looking for this today

**Comment by cvthub** [comment]
available in next release
