### ISSUE TITLE
[FEATURE] - Add Estimated USD Value for last week, yesterday and today profits

### ISSUE THREAD

**Issue by ahumadaz** [taniman/profit-trailer#253]
Add Estimated USD Value for last week, yesterday and today profits.

**Comment by Davethegithub** [comment]
Id like to see a Profit value in USD for every trade in the DCA & or PAIRS window.  % tells you nothing.  Satoshis is a pain to calculate and then work back to USD.  Exporting to excel is time consuming and to make things more complicated current value and total cost values are combined in one field such that you get a figure like 0.01254880.12345688 which have to be manually fixed.

**Comment by Concept211** [comment]
+1

**Comment by YoJeff** [comment]
My .02...  USD is worthless.   USD value as of when?   When the trade was made?  When the buy was made?  today?   How do you calculate a week?    This feels a bit like currency trading british pounds, but wanting to see the value in Indian Rupees.

**Comment by Concept211** [comment]
Just a simple estimated USD value based on the CURRENT conversion rate. Nothing complicated. It's just nice to give you an idea of the amount instead of looking it up or trying to estimate it in your head. Yes, if you look back at old trades, the USD equivalent will vary wildly, but again - just to give you a better frame of reference.

I know it's not the "right" way to determine gains/losses, but it helps as a frame of reference to our day-to-day currency.

**Comment by YoJeff** [comment]
I get the thinking, but...   The bots purpose is to accumulate BTC.   Subsequent conversions are tangential.  A profit booked, should be a profit booked.   When converting to USD a profit now is different from a profit in 10 minutes, is different from a profit yesterday.   It's a dangerous way to look at profit IMO.   Not to mention the majority of the world doesn't care about USD.   Why not show CAD, or INR, or AUD?

I really don't care either way.  It's mildly interesting to see total value in USD.   But development resources are finite.

**Comment by Concept211** [comment]
I thought about that too in terms of which currency to show since USD is only a small portion of the market. I'm with you on that. I just figured that Elroy already added the USD estimates on part of the dashboard, then why not in other areas. I'm with you though, I feel like this is very low priority compared to other important features like combining strategies for smarter trades and limiting buys based on long/mid/short term coin trends, etc. Anything to minimize these heavy bags! ;)

**Comment by YoJeff** [comment]
There is one currency.  BTC   💯 👍

**Comment by Concept211** [comment]
Well, anyway. For those who _want_ to view the fiat equivalent of your BTC values, you can use the Chrome Extension I wrote:
https://chrome.google.com/webstore/detail/bitcoin-auto-converter/jjcbgfhjneiblaifakgnnkdakebpebaf

**Comment by Davethegithub** [comment]
So Im from AUST and I do not want AUD used.   USD is the worlds reserve currency and most people use it as a benchmark - they literally think in it.  PT already uses USD on monitoring page.  Every exchange lists the value of all pairs in USD.  Its how most people ascertain value.  What is 0.00000395  in real terms -  I have no idea.... but if you say 0.03c I get it instantly no calculations required.  Information is power but if its cryptic its useless.

I might be talking about a different thing than you guys.  Personally I want this for a quick reference for individual live trades that are going south, on DCA and PAIRS page.  

When a trade is going south I need to know by how much at a glance.  I can then look at a chart and see whats going on.  Maybe the bot bought in at small dip on the top of a pump.  It doesnt know that.  Only a human can know.  Any trader worth 2 sats knows getting out in a timely fashion is the most important thing about trading.  The program does not hear the news nor understand FUD or that a coin can and will go to zero sometimes.  Stop losses are unsophisticated.  When a coin is crashing you do not want your DCA doubling up all the way down.  Some manual intervention will always be required.  this would allow me to be better informed at  glance and be very powerful for me.
