### ISSUE TITLE
Feature: different sell_values for different DCA levels

### ISSUE THREAD

**Issue by olberg** [taniman/profit-trailer#292]
If DCA level for a bag is only 1, I can wait a while to sell the bag. But if DCA level is 5, I want to sell the bag as soon as possible for 0% profit.
sell_value_1  = 0.5
sell_value_2  = 0.4
sell_value_3  = 0.25
sell_value_4  = 0.1
sell_value_5  = 0

**Comment by omarmoss** [comment]
@taniman 
Suggestion (Issue) https://github.com/taniman/profit-trailer/issues/292 is not the same as this.
This is in reference to Reducing risk with DCA levels.

Issue 292 is in reference to INCREASING trailing profits (for either DCA or PAIRS) the higher the profit goes, as it goes up.
Would you reconsider 292?

**Comment by Mikeeetrue** [comment]
Isn't it in 2.0 already?
DEFAULT_DCA_B_sell_value_20 = 0.1

**Comment by omarmoss** [comment]
Thanks for the interest @Mikeeetrue 

I don't see how?
What I want is:

#if the pair has a gain of x% already:
DEFAULT_(DCA)_trail_percentage_1 = 1
DEFAULT_(DCA)_trail_percentage_2 = 3
DEFAULT_(DCA)_trail_percentage_3 = 5
DEFAULT_(DCA)_trail_percentage_4 = 10

with:

#set this new trail based on current pair gain %, as set above:
DEFAULT_DCA_trailing_profit_1 = 0.3
DEFAULT_DCA_trailing_profit_2 = 0.6
DEFAULT_DCA_trailing_profit_3 = 1
DEFAULT_DCA_trailing_profit_4 = 2.5

The higher the gains for a pair at any given time, the greater the trail allowance.
Make sense?

This would allow for scalping as well as swing opportunities as they happen, instead of selling-out of a trade when the pair retraces for the next leg up (at each wave).

**Comment by omarmoss** [comment]
No comment before closing?
That's a shame.

**Comment by taniman** [comment]
@omarmoss  this issue was about different sell_values for DCA levels which has been implemented in PT 2.0

**Comment by omarmoss** [comment]
@taniman Still campaigning for 'issue' 216 referenced above.
https://github.com/taniman/profit-trailer-enhancements/issues/216

Thanks for all your great work on this great software : )
