### ISSUE TITLE
ChartData calculations on daily period not correct

### ISSUE THREAD

**Issue by vincent0923** [taniman/profit-trailer#327]
When using SMASPREAD and EMASPREAD, Changing SMA and EMA PERIOD have no effect. The spread is always calculated based on 300s.

**Comment by taniman** [comment]
If this were true @helmo would have pointed this out.  I will need some more factual data to look further into this. 

for now I will be closing this.

**Comment by vincent0923** [comment]
Hi, 
Understand that it's unlikely to have such a obvious bug, but I truly tested changing the MA Period and verified my finding based on chart data.  My conclusion is that MA Period is ineffective on SMASPREAD and EMASPREAD strategies. Based on data i can see on my bot monitoring page, the MA period is seemingly based on 300s. 

Dear Dev you can find that out within 5 minutes if you care to investigate.

If you need factual data, I'm happy to supply. 

Cheers

Vincent

**Comment by Helmi** [comment]
@taniman I haven't tested anything else but the default 300 as a period so far. #worksforme So don't count on me here to find that bug if it is one.

**Comment by taniman** [comment]
@vincent0923 have you tried restarting the bot after chaning the period. There is caching being done on chartdata as this is pretty expensive call on the api. chartdata contains a lot of data. 
So you need to wait 5 minutes or restart your bot.

Also I tested with 30 min chartdata before closing this . So I did take 5 mins to investigate.

**Comment by vincent0923** [comment]
@Helmi Hi Helmi, please test other periods, because longer period enables mid term and long term trades. Are you a tester of feature? then you should test other periods, otherwise how can you know I'm right or wrong?

@taniman I did restart the bot after changing the period, it made no difference. Tonight I did some more testing, I realised the BB_period is stuck at 300 too!!! I wanted it to trail DASH when the 1 day candle stick hits LOWBB (so i had BB_period = 86400; BB_sma = 15), but it started trailing just an hour ago, I quickly fired up TradingView and discovered that only the 5 minute candle stick hit the LOWBB. 

Unless you someone tell me 86400 is not a valid period and BB_period reverted to 300 default value?
86400 is definitely a legit period, it is 1 day in seconds, a standard period on all exchanges.

**Comment by taniman** [comment]
@vincent0923 helmi is jsut a user. But you were referring to emaspread and I know he uses it . as do I.

Now that you have provided me with more concrete and factual data I understand your problem and can tell you what is ging on.

You are trying to use daily charts with an sma of 15 days.  I told you before that chartdata is a costly call.  to make. that is why the bot currently has a hard limit of 2 days of chartdata that it reads. As most users only use the shorter candles the 2 days of data is enough to handle their needs. 
in your case you would like 15 days, so that's the problem you are most likely experiencing.
It's not about a wrong period being used, it's about not having enough data to calculate correctly

Can you contact me on telegram. I can have a version for you to test. shortly.

I will reopen this issue, but I will change the subject to something more accurate. unless you tell me that you also tried using shorter periods like 1 hour.
