### ISSUE TITLE
Coin Pair nomenclature across exchanges

### ISSUE THREAD

**Issue by jadiesel** [taniman/profit-trailer#346]
Just thinking. since every exchange uses a different format for coin pairs, perhaps the bot could be a little smarter about it.

Since we have the market already picked, (BTC for example), maybe we should just use the coin abbreviation in the settings, rather than 

     BTC-DOGE_sell_only_mode=true
     BTC_DOGE_sell_only_mode=true
     DOGEBTC_sell_only_mode-true

We could just enter 

     DOGE_sell_only_mode=true

Let the bot calculate how the coin needs to be formatted for the exchange.

**Comment by skazazes** [comment]
Would also bee nice if it was normalized throughout the webUI. As it is now, if you use the copy button in sales log for excel/sheets, there is no standardization to that the pairs are labeled as. This adds an extra step within the spreadsheet to normalize pairs from multiple bots.

Having it always appear to the user as BTC-XXX is all around more clean looking, both in settings and in the webui

**Comment by taniman** [comment]
@jadiesel I like the idea. Will look into it further. If it's achievable

@skazazes I do not like the idea of normalized output, because I know exchanges like to change stuff. 

For both of you here is problem.
Say we normalize to BTC-XXX
and in the background I go to Binance I make it XXXBTC
Now Binance decides to change its pair naming to XXX/BTC
Everybodies bot will be broken until I release an update. 
Because no matter what you type, The bot will keep converting to the invalid name

I am not looking forward to a day like that

**Comment by mkarulin** [comment]
How about normalize it only in CSV export?

**Comment by taniman** [comment]
(personal note )Add this based on a default configuration per exchange and pair overrideable configuration in configuration.properites
