### ISSUE TITLE
Manual DCA button

### ISSUE THREAD

**Issue by Helmi** [taniman/profit-trailer#360]
It would be good if we could have the possibility to easily manually initiate a DCA buy.

I'm thinking of a scenario with DCA completely disabled or only going to level 3 and by manually pressing a button you fire a DCA.

Of course this would need some more config probably but it would be good to have it.

**Comment by ZachGoldberg** [comment]
:+1:

**Comment by ZachGoldberg** [comment]
This would also be nice.  I have DCA disabled for most pairs as I'm not willing to double down on every pair, especially if i'm not watching closely.  Every now and then though I am watching closely and I'd like to manually double down / DCA on a pair just to have a higher chance of clearing it out / restarting the cycle.

**Comment by cryptt** [comment]
While a manual DCA button would be awesome, I imagine it will take more effort and coding.
Since there is a hotconfig option now in the new version I would be nice to be able to achieve this by using this option.
XXX-BTC_DCA = true which would make it dca 1 time. I guess it would be best if this option would supercede any other settings like max_buy_times, max_cost and min_buy_balance
@taniman 

Cheers

**Comment by swoopsus** [comment]
+1

**Comment by sil3ntcor3** [comment]
+1

**Comment by taniman** [comment]
Added in 2.1.0
