### ISSUE TITLE
Binance - BUY Amount - Fee

### ISSUE THREAD

**Issue by flyboy1** [taniman/profit-trailer#361]
![bina-wtc](https://user-images.githubusercontent.com/15215265/33607396-442ec782-d9c1-11e7-862d-fe07acfc1d0d.JPG)
At Binance there is a big chance of dust if PT buys a coin with All_max_cost and is forced to use a rounded value when selling after the fee is deducted.

Example: 
All_max_cost = 0.0015

PT buys 2.0 WTC -- then charges will be deducted 0.002 WTC -- and 1.998 WTC will be available in the Wallet.

Possible SELL values are only integers. i. e. I don't have 2 and 1 WTC is below the minimum fee.

1.998 WTC = DUST (0.0015xx BTC)!!

**Comment by cryptotrader-1** [comment]
This is a big issue because when you dca this case you get stuck in an error loop.

**Comment by taniman** [comment]
I do not understand this issue. If you know the problem is the way binance works. What are you proposing? It's not an issue if that's how binance works

**Comment by flyboy1** [comment]
I think I understand how Binance works. 

If the BNB were to be integrated into PT for paying the fee, Dust then would be no problem. 

Currently, it is definitely a dust creator if the fee is deducted directly from the purchased coin after the purchase.

As in example. WTCBTC can no longer be sold from my sample above. 
BUY: 2 WTC Coins - Fee 0.002 WTC = 1.998 WTC and now SELL is impossible. 
Why? 1 WTC is to small and 2 i don't have any more. There is no decimal enabled for SELL only Integer Values.


It may be that some people with a higher max cost might not notice this problem, but with ALL_enabled_pairs = ALL
it can quickly generate a lot of dust. 

I hope you understand my machine-translated English.  (-:

**Comment by Fogazi** [comment]
I understand, in the 24 hours I have had PT on Binance I have at minimum 10 pairs at dust levels.
Because of the sell only integers, ever sell will leave dust.

IE, bot made a buy for 8 IOTA last night, deducted the 0.1% fee which is 0.008 IOTA. So now left with 7.992 IOTA.
The bot then makes a sale and due to the sell integers only, it sold 7 IOTA which leaves me with .992 IOTA which is less than Binance minimum trade == dust!.

Just thought I would add this to help explain.
Obviously when BNB is implemented into PT this will eliminate this problem. Can't wait devs, great work so far.

**Comment by cryptotrader-1** [comment]
I think the problem I had was that it would do the case fogazi described and then with hidedust=true it would still show dust and would be caught in an error loop.
I fixed my issue by putting hidedust=false then BTCdust=0.00099
