### ISSUE TITLE
It's seems that the bot freeze (no more Profit# update) when there are too much long trailing in Possible buy, Pair and DCA

### ISSUE THREAD

**Issue by AkliOnet** [taniman/profit-trailer#410]
Then I restart and I see the Profit% that are completely different.
Anyone else has the same problem?

**Comment by krims0n32** [comment]
I have a somewhat similar issue. Bot is missing pairs that are present on the exchange. TCV is not displayed properly. When I restart the bot it is working again. I see the 3 heartbeats in the logs regularly and no errors.

**Comment by taniman** [comment]
See #204 , this is a know issue and I am still trying to investigate. The problem is mostly related to users machine. So it is not something that can be fixed just by chaning something in the logic

@krims0n32 if oyu see 3 heartbeats just before you restart your bot. than there is nothing wrong with the bot. You need to make sure you are not buying dust amounts
