### ISSUE TITLE
4 profitable trades and yet lost on Binance

### ISSUE THREAD

**Issue by cryptt** [taniman/profit-trailer#421]
Hi all,
I just started a second bot on Binance.
I had exactly 0.2btc on the exchange. I choose not to use BNB
Now the weird thing. I made 4 trades with profit within the hour and yet I lost some BTC
![screen shot 2017-12-15 at 22 21 09](https://user-images.githubusercontent.com/34436021/34048550-b23157f4-e1e6-11e7-8b93-b22b0ace3088.png)
My trades all won right?

![screen shot 2017-12-15 at 22 21 18](https://user-images.githubusercontent.com/34436021/34048564-bf7f00fa-e1e6-11e7-8a23-4d4c5bbf4b41.png)
I have according to this 0.00021035BTC profit
and yet my balance went from 0.2 to...
![screen shot 2017-12-15 at 22 26 29](https://user-images.githubusercontent.com/34436021/34048651-164be808-e1e7-11e7-91e4-7e66b521f804.png)
I asked on the PT telegram chat and they said don't worry on Binance it wil show the correct balance.
![screen shot 2017-12-15 at 22 26 47](https://user-images.githubusercontent.com/34436021/34048693-370ab61e-e1e7-11e7-9c29-88406b67a179.png)
Not, it's the same.

Just to be clear this is a fresh account no other trading has been made so I don't have any dust laying around.

Can it be that the bot did not calculate the Binance fees?

I stopped the bot within the hour as I'm not a charity for BINANCE.

Anybody else has this problem??

Using version 1.2.6 on a VPS server unbuntu 16

**Comment by cryptt** [comment]
![screen shot 2017-12-15 at 22 50 26](https://user-images.githubusercontent.com/34436021/34049555-69eb3006-e1ea-11e7-9e91-3b88f2025214.png)
'full' history from binance

**Comment by taniman** [comment]
This is your balance. Now go to your binance account and have a look at what binance tells you your total balance is.

Because binance leaves a lot of dust behind if you are not paying your fees using BNB.
And dust amounts also are part of your portfolio and total balance.

![image](https://user-images.githubusercontent.com/6751341/34049565-2a480884-e1b8-11e7-91ab-1602430ee3a4.png)

Does this page also show you les than 0.2 BTC?

**Comment by taniman** [comment]
You should look at TCV in the bot (But in the current version dust is hidden). Also what the bot shows is a guidance.
Yuo should always look at your exchange. That's your real true account balance

**Comment by cryptt** [comment]
Okay so how does the bot calculate the fees?

**Comment by cryptt** [comment]
Oh I see now you mean at deposit and withdrawals.
So if pay the fee in BNB the bot knows this and takes this into consideration?

**Comment by taniman** [comment]
so did deposit and withdrawals show you a better balance?

the bot get's the fees information from your exchange and calculates the average price after the fee. 
for selling. the profit being displayed is always 0.20% less than the actual profit you made on that trade. You can calculate for your self and see.
So fees are always taken into account. 

The problem with binance. And a lot of people on the main channel know this. 
if you buy 2 XRP and do not pay the fees with BNB you are left with 1.95 XRP

but on binance XRP cannot be sold with decimals. So you can only sell 1 XRP. The rest will become dust.

so once you sell, your balance will not increase as much as you taught because you still have some XRP left that is not sold.

if you use BNB to pay for fees. 

when you buy 2 XRP, you will still have 2XRP left, as the fee is  taken from your BNB balance.
so when trying to sell, you will always sel the complete 2XRP you have. and no dust.

You will need to buy BNB on binance.
make sure the setting to pay fees  with BNB is turned on
in the bot  disable trading of BNB
BNBBTC_trading_enabled = false (BTC market)
BNBETH_trading_enabled = false  (ETH market)
BNBUSDT_trading_enabled = false (USDT market)

**Comment by cryptt** [comment]
Thank you for the explanation I've changed it already.
