### ISSUE TITLE
REQUEST: Price rise/fall in base market other than BTC, i.e. ETH, USDT, BNB etc.

### ISSUE THREAD

**Issue by ZachGoldberg** [taniman/profit-trailer#424]
It'd be great if PT could turn on SOM if the base currency / market moves up or down more than x%.  The BTC triggers are great, would love to have them for ETH, USDT, BNB etc. as well!

**Comment by johnalindogan** [comment]
i'm starting to filter my enabled coin pairs based on their 24hr % change. if i feel that a pair is already too high, say +50%, i would want to enable SOM for that pair. i'm hoping to enable only pairs that would have more potential for an uptrend, rather than trading pairs that are already at ATH.

This feature request would work for that strategy i think

**Comment by symbion6** [comment]
+1
