### ISSUE TITLE
Market_Coin_Rise and _Drop option

### ISSUE THREAD

**Issue by Zombato** [taniman/profit-trailer#430]
We need an option similar to btc_rise and btc_drop. A few days ago ETH mooned whiled BTC was flatting. That created lots of bags, cause trigger wasn't activated at all.

ofc this option must work for non-btc markets only

**Comment by taniman** [comment]
See #424

**Comment by johnalindogan** [comment]
i'm starting to filter my enabled coin pairs based on their 24hr % change. if i feel that a pair is already too high, say +50%, i would want to enable SOM for that pair. i'm hoping to enable only pairs that would have more potential for an uptrend, rather than trading pairs that are already at ATH.

This feature request would work for that strategy i think.
