### ISSUE TITLE
PT bought more pairs then set limit. 

### ISSUE THREAD

**Issue by MattWellman** [taniman/profit-trailer#437]
Hello, 
Bug report info below, 
ALL_max_trading_pairs = 3
fourth pair bought.

![image](https://user-images.githubusercontent.com/5161716/34086353-21925df4-e369-11e7-8fbf-9558579a9ae8.png)
![image](https://user-images.githubusercontent.com/5161716/34086358-2c114740-e369-11e7-80f6-c51726699e0d.png)
![image](https://user-images.githubusercontent.com/5161716/34086367-396b3fa4-e369-11e7-96d1-a5cd54d29c4d.png)

**Comment by automaticprofits** [comment]
Hi Matt,

Yes it is happening to me too.  This is definitely concerning because opening multiple initial trades will consume more capital than expected and leave less for other initial trades and worse yet....not enough for the DCA trades.

Since I am not very savvy on how to use Github, do you know how to add a suggestion for the dev team here on Github about perhaps having a ie. Min Cost = $75 and a Max Cost = $80

This way the amount invested per trade can be contained within those parameters.

Mike

**Comment by taniman** [comment]
You are both having problems caused by bittrex API issues.  I will be building some more defensive logic again these issues in V1.2.6.1

**Comment by Shaping** [comment]
I had the same kind of problem on Binance.
