### ISSUE TITLE
How we start sell only mode as in 1.6.2 binance removes btc triggers

### ISSUE THREAD

**Issue by abhirb1** [taniman/profit-trailer#471]
[Binance Exchange]
No support for consecutive buy triggers
No support for BTC rise and drop triggers (IP ban enhancements)
Missing 24h change and trend percentages (IP ban enhancements)

How should we enable sell only mode now?

**Comment by Fogazi** [comment]
ALL_sell_only_mode = true in pairs config

**Comment by abhirb1** [comment]
@Fogazi That will be static, but i need something dynamic. Can we do that?

**Comment by abhirb1** [comment]
@Fogazi I think this is a big problem, if there is no rise and drop trigger then there is big risk while trading on Binance. On Bitrex new signups are suspended and Poloneix has lots of support problem. Can you please guide next?

**Comment by tollivne** [comment]
I'm a newbie, purchased PT yesterday and doing my research to understand and customize my settings.  Got error message about consecutive triggers not supported on BINANCE, so I'm commenting them out of my code.  This concerns me because I might be at work with PT running at home and unable to stop it when the market takes a huge spike or big dip.  Any thoughts on the matter?  Workarounds?
