### ISSUE TITLE
[Feature Request] Reserve amount of coins

### ISSUE THREAD

**Issue by mrlex** [taniman/profit-trailer#496]
Good day everyone, 

I've been browsing the issues and I did not find what I was looking for. If it's already been submitted I am truely sorry. 

Would it be possible, or practical, to have a function to "reserve" a certain amount of coins to hold? 
Example, I just bought 1000 XRP, PT sees that I bought it and it shows in my pairs log with the price and everything. I then disable trading in the settings (BTC_XRP_trading_enabled = false) which puts XRP in watch mode.

But what if PT spots a profit occasion on XRP? I don't want it to sell my 1000 XRPbut I still want it buy some if an opportunity comes along. Hence the feature "BTC_XRP_reserve_amount = 1000" might come in handy, no?

Anyway, as I said, sorry if this has already been asked, or if it's already implemented, I just couldn't find the info.

With that said, have an excellent day and I wish you all the best for 2018 and many profitable trades :)

Alex

**Comment by steveoneal** [comment]
This would be a good idea.

**Comment by vicenterusso** [comment]
+1

**Comment by mrlex** [comment]
@taniman Thank you very much for your work and the fact that you take the time to listen to us! :)

**Comment by m59peacemaker** [comment]
I haven't used PT yet, but I wonder what happens if you put in a limit order to sell that XRP at a really high price. PT wouldn't cancel the order to get the coins and use them, would it?

**Comment by matt5784** [comment]
+1 I think this "reserve" would be really good for both long-term holds (where you still may want to trade on the volatility) and also on Binance to hold some BNB for fees but still trade that as well.

**Comment by lukasp2** [comment]
A very good idea!

**Comment by a7777777v** [comment]
+1 WOULD LOVE THIS. Yes Please :)

**Comment by Ruzefix** [comment]
I just wrote a feature request and now I find _THIS_ ^^
Maybe my text is obsolete now but I'll append it anyway instead of opening a new issue  ;)
############################################
Feature Request: HOLD_MIN_XXX

It would be nice to have a feature which would allow to trade coins but hold a fixed amount of them.
Actually it's only possible to hide or exclude them completely :(

Example for Binance: BNB
BNB is volatile enough to trede with but because of the fees we have to exclude or hide them.

Another example: I loaded my exchange with 10 XXX from my wallet to trade with them. Step for step I want to increase the amount of holding XXX of them to send the same amount back to my wallet (should be only one transfer because of the fees).

XXX should be normal bought but hidden/substracted from available volume.

Maybe calculated like this:
Inital XXX amount is 0.


HOLD_MIN_XXX = 10

PT: Oh, market looks fine, I buy 5 XXX
(available for trading: 0)
PT: Fine again, I buy 7 XXX
(available for trading: 2)

Intension is not to force buying XXX until the hold value is given (would be nice for BNB but manually buying works fine, too) but not to sell below the given value.

**Comment by cryptoluck** [comment]
That would be awesome!

**Comment by a7777777v** [comment]
this feature will be huge, looking forward to it!

**Comment by alexpica** [comment]
+1

**Comment by sirloinwesk** [comment]
+1

**Comment by tooraj-enayati** [comment]
Should be done by COIN-PAIR enabling ALL_max_cost_percentage & ALL_max_cost so we can reserve some coins (eg. BNB)

**Comment by kmf88** [comment]
Would be awesome, cant wait.    I only trade BNB and would help out allot.  Thank you for all the great work on PT!

**Comment by flybuzz** [comment]
+1 Please add!

**Comment by niroshana35** [comment]
+1 for this feature

**Comment by taniman** [comment]
Added in 2.1.0
