### ISSUE TITLE
Mismatch between Binance Acccount value and PT TCV

### ISSUE THREAD

**Issue by vbootstrap** [taniman/profit-trailer#541]
An example of what I am talking about is:
Binance is showing my current account value as 0.06219295 BTC
PT is showing my TCV as 0.05779272BTC

at the same time PT is showing the TPV as 0.05658247BTC

**Comment by jsnx** [comment]
Please check the following: 
a: Current value of sales log (directly in the log at the bottom of the page)
b: Current value of DCA log (directly in the log at the bottom of the page)
c: TCV on the Monitoring page or at the top of the page.

a and b summed up should equal the TCV. They don't, right?

Why? Because of the dust log. PT seems to add the amount of funds you need to sell you dust and add that to the TCV. 

Is this really solved now?
