### ISSUE TITLE
[REQ] Don't hide monitor summary during refresh.

### ISSUE THREAD

**Issue by YoJeff** [taniman/profit-trailer#580]
The blinking in and out doesn't really convey anything.

**Comment by acefed** [comment]
This is (in my personal case) caused by polling coinmarketcap.com every few seconds, as follows:

https://api.coinmarketcap.com/v1/ticker/?convert=usd&limit=21&_=1234567890123

The PT webinterface does 3 requests:

2 for the PT application itself. I receive these replies within max. 50ms, with my PT running remote in a VPS.

1 for coinmarketcap.com (usd conversion rate, I assume). This one takes up to 5 or 10 seconds, sometimes timing out completely. During this wait, no data is visible on the dashboard top.

With multiple dashboards open, one IP-adress bombards their api, probably causing more delays as they might be throttling them.

PS: You can check the loading times of these api calls by opening the browser console (F12 in Firefox), en looking at the network tab.

**Comment by djcrypto75** [comment]
Will fix this. Have a solution.
