### ISSUE TITLE
[FEATURE REQUEST] Arbitrage Bot

### ISSUE THREAD

**Issue by alcar2** [taniman/profit-trailer#617]
It would be great if PT could build up an Arbitrage Bot to benefit from the price gaps between the available exchanges. Good for Bitcoin as well as Alts. If there is a gap, short one exchange and long the other until the gap closes. Any thoughts?

**Comment by YoJeff** [comment]
I'm thinking this is a separate bot.

**Comment by alcar2** [comment]
I agree

**Comment by LoganH1985** [comment]
The gaps exist because of fees to transfer money generally. you would yield really no portfolio benefit from trying to Arb between exchanges WITHOUT transferring funds to said exchange. The benefit you CAN get out of this is when you have BT in one exchange that is lower and are pulling it out. It makes it less likely that the confirmation time will have as much of an impact on your withdraw if the USD withdraw exchange, such as Gemini is priced higher.

**Comment by alcar2** [comment]
I don't agree. As example, type in Tradingview's formula bar: "BIITREX:BTCUSDT-BINANCE:BTCUSDT". You see the gaps there? The gaps are even higher for Altcoins. You don't have to withdraw any funds. Short on one exchange and long on the other. Short the one that is most likely going down.

**Comment by YoJeff** [comment]
Not on the roadmap.
