### ISSUE TITLE
Incorrect bought price. PT sells in minutes cause it thinks huge profit has been made

### ISSUE THREAD

**Issue by timh77** [taniman/profit-trailer#651]
I have had a few of these tonight. PT is buying coins on Binance, reports an incorrect "Bought Price" and after a few minutes sells it again. Thinking huge profits have been made. In this case I was quick enough to reset the price thru hotconfig.

![dump](https://user-images.githubusercontent.com/14058767/34848358-c96b5792-f71e-11e7-9ece-79906f70510d.JPG)

Log:
0|profit-t | 2018-01-11 22:25 +01:00: 2018-01-11 22:25:33 INFO ProfitTrailerService - Buy order for EOSBTC -- {"symbol":"EOSBTC","orderId":10721204,"clientOrderId":"PLATsNzUwWzjzPnbj9LH1f","transactTime":1515705933622,"price":"0.00086487","origQty":"3.00000000","executedQty":"3.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}
0|profit-t | 2018-01-11 22:25 +01:00: 2018-01-11 22:25:39 INFO ProfitTrailerService - Get order information -- {"symbol":"EOSBTC","orderId":10721204,"clientOrderId":"PLATsNzUwWzjzPnbj9LH1f","price":0.00086487,"origQty":3.00000000,"executedQty":3.00000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY","stopPrice":0E-8,"icebergQty":0E-8,"time":1515705933622}
0|profit-t | 2018-01-11 22:25 +01:00: 2018-01-11 22:25:39 INFO NormalStrategyRunner - Normal Pair - EMAGAIN bought -- currency pair EOSBTC - BV -0.49, BVL 0.0, MTP 15, TTP 14
0|profit-t | 2018-01-11 22:25 +01:00: 2018-01-11 22:25:45 INFO AverageCalculator - EOSBTC - Price mismatch of 100.000000 %. Let me recalculate

**Comment by timh77** [comment]
And something similar...

0|profit-t | 2018-01-11 22:35 +01:00: 2018-01-11 22:35:28 INFO ProfitTrailerService - Buy order for LENDBTC -- {"symbol":"LENDBTC","orderId":3054660,"clientOrderId":"VBfdhpMqr5vERJnDfY3cFZ","transactTime":1515706528285,"price":"0.00002010","origQty":"149.00000000","executedQty":"149.00000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}
0|profit-t | 2018-01-11 22:35 +01:00: 2018-01-11 22:35:33 INFO ProfitTrailerService - Get order information -- {"symbol":"LENDBTC","orderId":3054660,"clientOrderId":"VBfdhpMqr5vERJnDfY3cFZ","price":0.00002010,"origQty":149.00000000,"executedQty":149.00000000,"status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY","stopPrice":0E-8,"icebergQty":0E-8,"time":1515706528285}
0|profit-t | 2018-01-11 22:35:33 INFO NormalStrategyRunner - Normal Pair - EMAGAIN bought -- currency pair LENDBTC - BV -0.49, BVL 0.0, MTP 15, TTP 15
0|profit-t | 2018-01-11 22:35 +01:00: 2018-01-11 22:35:40 INFO AverageCalculator - LENDBTC - Price mismatch of 3.355705 %. Let me recalculate
0|profit-t | 2018-01-11 22:35 +01:00: 2018-01-11 22:35:40 INFO AverageCalculator - LENDBTC - Price mismatch of 5.0, Let me recalculate...
0|profit-t | 2018-01-11 22:35 +01:00: 2018-01-11 22:35:40 INFO AverageCalculator - Please set LENDBTC_bought_price

Knowing the orderid, can't PT get this information from Binance (or any other exchange)?

**Comment by Kevone8** [comment]
I had the same problem. It was sold twice at a loss, and I just happened to catch it, otherwise it would have just happened over and over again. Scary, please help.

Summary:
Just noticed that my PT bought NEBL on Binance, listed as 'Bought Price' of 0.00165369 and immediately sold reporting 38% profit. Would be nice if true; however, I checked my Binance orders, and I actually LOST money. I noticed it because it had went into DCA, and went it bought the 1st level of DCA, it immediately thought it had made 38% profit and sold, but it wasn't accurate. Afterward, it bought it again and sold it again at a loss. Each purchase after this firstDCA was incorrect and always a bought price of 0.00165369. Around the same time, I had this error in the logs 2018-01-11 16:33:23 INFO DCAStrategyRunner - NEBLBTC, mc 0.15, ctc 0.004433088, dbc 0.009029183999999999, bb 0.09396463 2018-01-11 16:33:23 INFO DCAStrategyRunner - DCA - Anderson bought -- currency pair NEBLBTC - CP -3.5466622107110046 - BT - 2018-01-11 16:33:32 INFO AverageCalculator - NEBLBTC - Price mismatch of 50.000000 %. Let me recalculate 2018-01-11 16:33:32 INFO AverageCalculator - NEBLBTC - Price mismatch of 1.92, Let me recalculate... 2018-01-11 16:34:34 INFO ProfitTrailerService - Sell order for NEBLBTC sold amount 3.840000 for price 0.002290 -- {"symbol":"NEBLBTC","orderId":1876766,"clientOrderId":"USVLFHe4EZKZ8BI2Dj3zts","transactTime":1515706474892,"price":"0.00229000","origQty":"3.84000000","executedQty":"3.84000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"SELL"}(edited)

**Comment by taniman** [comment]
Have you set any buy prices in your pairs.properties?
.Binance was having issues last night.

And yes we do get the prices from binance. But its a bit more difficult than that

**Comment by timh77** [comment]
@taniman : what would have been nice is that PT would set the Bought Price to 0 in case it is unable to retrieve all buys for the same pair. I have had 5 occassions when pairs were in DCA, a DCA was triggered and the bought price would get set to price the current price. I guess it couldn't calculate the average buying price.

And yes, Binance had issues. But in my opinion software should be able to handle a situation like this. It should be possible to sell a position in this case.
