### ISSUE TITLE
[Feature Request] Average Min Volume

### ISSUE THREAD

**Issue by vicenterusso** [taniman/profit-trailer#708]
I'm using min vol 800 and PT bought a lot of shitcoins. Having an _average_min_buy_volume_ "x" for "y" past days would be a nice addition for pump&dump protection

**Comment by jalapeno777** [comment]
Yup.  I've been caught by a few of these...not from the P&D itself but because the volume is higher for the day the bot doesn't realize that the price point is way off base.

Another option is to be able to filter from buying coins that are within a % of the high 24h price for the day (compared to the low).  This way if a coin is hitting it's peak or recently hit it's peak I can avoid it until the coin settles a bit.

**Comment by aaronssu** [comment]
+1

**Comment by DavidLanz** [comment]
i concur with you guys

**Comment by YoJeff** [comment]
If any/all of this request is still valid, resubmit in the issues github here:  https://github.com/taniman/profit-trailer-enhancements/issues
