### ISSUE TITLE
[Feature Request] Please add more SELL strategies

### ISSUE THREAD

**Issue by antknight** [taniman/profit-trailer#719]
The only sell options are HIGHBB and GAIN. I would like to see other options like EMACROSS and EMAGAIN for SELLING

#717

**Comment by designMalachi** [comment]
Yes I would like use EMACROSS as a sell strat as well. Send me a beta?

**Comment by swanfield1979** [comment]
I would love EMACROSS aswell. I hope there could be a trailing and min_profit with that.

**Comment by ricardodacosta** [comment]
Also interested in EMACROSS as a sell strategy!

**Comment by empbac** [comment]
EMACROSS seems to be a favorite everywhere.

There is another thread requesting trailing_profit on HIGHBB sell strategy. These projects might be best tackled together at a later time as some reworking of sell strategy in general looks required for these to happen. I would assume that at this point it's not trivial to make any sell strategy also trail, and trailing is what makes Profit Trailer Profit Trailer.

**Comment by swanfield1979** [comment]
For EMACROSS I don't think trailing is usefull on this. And ofcourse a name is just a name :-)

**Comment by bitcointrucker** [comment]
As someone who's interested in using EMACROSS sell strategy, I don't think "trailing" is really needed for what I intend to do with it. As soon as the cross occurs the 2nd time, I want it to sell NOW, because it's more than likely entering a bear trend (at the top), so I want it to sell ASAP. Min_profit would be nice to have, though, because sometimes after a small cross it ends up in a downtrend. Another idea would be, could max_spread be something that could be defined as a minimum OR a maximum (ex: max_buy_spread and min_buy_spread). This would be helpful in detecting the difference in a sideways market and a bull run. Just another suggestion. Hopefully we see this feature soon! Thanks!

**Comment by PutraBit88** [comment]
Also just thinking about this which we can use 2nd EMACROSS for the sale part, as it did for the first cross (upper) with positive % SMA2 cross SMA1 to trigger BUY, we can use it as well for trigger SALE for 2nd cross (lower) with negative % and with condition min profit =1 

ALL_sell_strategy = EMACROSS
ALL_sell_value = -0.5
ALL_min_profit = 1

**Comment by jaminess** [comment]
Ya that would be awsome!!
