### ISSUE TITLE
Sell strategy: HIGHBB + trailing option

### ISSUE THREAD

**Issue by japsen** [taniman/profit-trailer#726]
When using HIGHBB sell strategy, I would like to have the _option_ to allow the bot to start "trailing" once the HIGHBB level is reached. Currently it looks like the bot will instantly sell if the calculated HIGHBB level is reached.

**Comment by symbion6** [comment]
+1
Wiki states "Use with **gain** strategy to try and maximize your profit."
It would be fantastic to have this with HIGHBB. Profits can be much higher with this enabled.
It now just chops off the profit at a static value. Instead, let it trail like with gain strategy, until price drops by the set percentage.

**Comment by m59peacemaker** [comment]
It seems like the solution for this and similarly for #1247 is to separate the two behaviors of "buy_value" and "sell value" into two settings: `buy_trailing_trigger_value`, `buy_value_limit`, "sell_trailing_trigger_value" and "sell_value_limit", where `buy_trailing_trigger_value` is the value from which the bot starts following the price down, and `buy_value_limit` is the highest value the price can be and a buy still occur. Just like usual, but two settings instead of one.

```
# start trailing when the price just touched the LowBB
ALL_buy_trailing_trigger_value = 0

# buy even though the price is now higher up from the LowBB
ALL_buy_value_limit = 2

# start trailing when the price is 1% before reaching the HighBB
ALL_sell_trailing_trigger_value = 1

# sell even though the price is now even further below the HighBB (as long as min_profit is also met)
ALL_sell_value_limit = 5

#
ALL_min_profit = 1
```

An example is:
The price touches the LowBB (0%), so the bot starts trailing the price down, because `ALL_buy_trailing_trigger = 0. The price goes down, then jumps up by the trailing buy value, but the price has now risen to 1% above the LowBB line. ALL_buy_value_limit is 2, and 1% is less than 2, so the bot puts in a buy order. This buy would have been missed with the current `buy_value`, since the price had risen above it.
Similarly, the price rises and nearly touches the HighBB (1%), so the bot starts trailing the price upward. No matter what, you want to make sure you sell here. The price ends up falling back to a decent bit below the HighBB to 4%. You still have at least your `min_profit` of 1%, and you are close enough to the HighBB (4%) to not exceed your `sell_value_limit` of 5%. The bot sells.

**Comment by YoJeff** [comment]
All sorts of new sell strategies in v2.x.    If any/all of this request is still valid, resubmit in the issues github here:  https://github.com/taniman/profit-trailer-enhancements/issues
