### ISSUE TITLE
Hotconfig (re)set DCA count

### ISSUE THREAD

**Issue by GeorgeBIV** [taniman/profit-trailer#739]
Occasionally I'll make a manual buy and PT will show it in the log using a previously (fully) sold DCA level, would like to be able to have it function like a newly bought pair without having multiple DCA levels attached to it.

**Comment by taniman** [comment]
Well the software was not designed allow manual buys just like that. This just brings more complexity than needed. 
But let's see what can be done

**Comment by m4rc3l** [comment]
Setting the DCA Level to a pair manually would be good. It happened to me that my json got corrupted due to power outage, some paris in DCA were already on lvl 5 but still around -10% profit. Once the bot was up again the DCA levels were at 0, so it was instantly buying  2-3 DCA-levels for a big amount....

**Comment by RunPlz** [comment]
I had this issue as well in .20
I believe this can be merged into DCA enchancements
