### ISSUE TITLE
Revise Binance throttle mechanism

### ISSUE THREAD

**Issue by taniman** [taniman/profit-trailer#741]

**Comment by Tank33au** [comment]
I dont really know the details of what information the bot seeks but I cannot understand why the bot needs to make enquiries to get us banned.
Since binance changed the api policy and we have the bandage on the PT. 
PT is very slow to reflect any configuration changes or price changes. 

I think PT needs to set a priority to what information it seeks from the exchange.
1. The pairs that has triggered sell and trailing
2. The pairs that has triggered buy and trailing
3. The pairs that is going to trigger sell
4. The pairs that is going to trigger buy

Not every pairs we hold is equal. Ignore the ones thats doing nothing and spend more resources on the pairs that's going to make a profit soon.
Do we really need to know what is the new price of the pair that's sitting at -15% every few mins? I dont think so.
Dust log only need to get updated once a day kinda thing.
