### ISSUE TITLE
Combine multiple strategies + Add RSI + MACD

### ISSUE THREAD

**Issue by taniman** [taniman/profit-trailer#82]
Nou RSI is een van mijn eerste indicatoren die ik leerde en volgens mij een van de makkelijkste
 als ie boven aan is is de verwachting dat ie naar beneden gaat als ie onderaan staat de verwachting dat ie naar boven gaat
 dus bijvoorbeeld bovende 70% is verkopen onder de 30% is kopen
 en dat met bollingerband.... en je hebt een super robot

**Comment by scoutband** [comment]
For the rest of the world :-)

Well, RSI is one of my first indicators I learned and I think one of the easiest
if it is on top it is expected that it will go down if it is below the expectation that it will go upwards
Thus, for example, over 70% is selling below 30% is buying
and that with bollingerband .... and you have a super robot

**Comment by minerdude** [comment]
Will be very useful

**Comment by Utone** [comment]
I will copy my github post for the other bot where I was the first to suggest implementing RSI (then only thinking of avoiding dump) sand as time went by kept pestering the dev to finish the damn prototype ;)

It now has incorporate RSI into some strategies, some that would greatly benefit would be DCA and it just gives great gains 3-5% set as a minimum for pairs...

Ok to get on with it, you might have looked in to it already but this:

The common standardly used RSI period is 14 days..
After noticing RSI level changes with different time periods and tweaking with scale in tradingview, because I assumed the same ultimate low or high peak would result in the same RSI value across time periods. Nope of course not..: lol That would make it too easy right??

In general the longer the timeframe the less RSI is affected:
https://s.tradingview.com/x/y5LrsNqX/ see how that first small dip would trigger a bad buy signal?
https://s.tradingview.com/x/O3Yua94H/
https://s.tradingview.com/x/Jg2JKpI1/
https://s.tradingview.com/x/RVT14MNl/ at 30 minutes you might get lucky and get a buy
https://s.tradingview.com/x/f5XIvcs2/ Here at 1 hour it isn't oversold..

But I did find something interesting: RSI period setting.
You could use this to tune the sensitivity, so that even if you change your Time Period used from, say 15 to 5 minutes you can check in advance what time period levels out the difference in sensitivity so it best corresponds to the 5 minute output.

And reducing the RSI period results in more buy and sell signals.
7 days would fit some pairs nicely... Some traders even go as low as 2 days (basicaly Stoch RSI:)) , Anyway great for us short term traders using 15, 5 or even 1 minute periods a lower RSI period (or at least the ability to adjust the sensitivity would greatly improve the indicators profitability..
And use it as a more dependable indicator and we can tune it to a coins behaviour (in override) so it matches up the general strategy (used as a catch all pairs, handy for when market changes)

Very often this setting can greatly improve a coins performance with RSI based strategies.
I have not dived into accuracy settings but i suspect it to be subtle but they are available in the tradingview default RSI indicator. (now also used in Sjakil's Zeno GUI)

http://tradingmarkets.com/recent/why_rsi_may_be_one_of_the_best_short-term_indicators_-673367.html

**Comment by bbrodka** [comment]
RSI2 < 10 is  a great entry point, combined with some  other indicators
Also Multiple time frame indicators would be nice
Say longer time indicator 1 hr bars (Wider view of price action) combined with shorter time 5 min  indicator for buy triggers

**Comment by symbion6** [comment]
+1 Klinkt goed! (sounds good)

**Comment by wahbalami** [comment]
add more indicator and combine them the bot is getting lot of DCA bags, wake up

**Comment by wahbalami** [comment]
addddddddddddddd indicators and let the users decide either yes or no to use them don t decide ur self. you are dealing with people and costumers right?
