### ISSUE TITLE
Important command line implementation - More Profits

### ISSUE THREAD

**Issue by Binildos** [taniman/profit-trailer#844]
Hey guys, whats up? I'm using PT now for about a week. When I was studying my sales I realized that most of the time, the trigger profit percentage is way higher than the profits of that coin specific sale. So I was wondering, what if we could set a stop gain profit at x%? What would probably happens is that the bot will sell things faster, since most of the time it doesn't sell for a great value anyways. My point is, maybe is better to have several 2% gains in the same period of time that we have a once and a while sale of 5%... So, can you check if it's possible to implement a command line that we could insert so whenever we wish for, we can set a stop profit (gain)? Can it be done? Thanks in advance!

**Comment by Binildos** [comment]
In addition to my previous comment, if there is a way for the bot to establishes a sell trigger based on the profits, it would be awesome... I mean, the same way bot buys more when reach a certain trigger, it should have an inverse trigger, so when the profits go up x%, the bot will sell the coins when it comes back to that x%...

**Comment by taniman** [comment]
Do not add multiple requests in 1 issues. and next to that if you want to sell a coin immediately. you can activate panic_sell for that coin

**Comment by empbac** [comment]
This exists in Profit Trailer already, it's the ALL_trailing_profit parameter. You offset your exchange fees with ALL_min_profit (.5 for Bittrex, .1 for Binance, Poloniex who knows), and then you set your minimum profit level with ALL_sell_value -- this last parameter appears appears in your Pairs list in the GUI as "Trigger%." The bot will not try to sell until your profit is higher than the Trigger%. Then, it trails the profit by the amount set in your trailing_profit parameter. Once the amount comes down by the specified percentage, AND still holds above the Trigger%, that's when a sell order is placed. This is why you're seeing Profit% as lower than Trigger% in your Sales Log.

You can try to sell as soon as a coin goes positive by temporarily changing your settings so that sell_value is 0 and trailing_profit is 0. I do this sometimes when a pair is hovering right over the 0% profit line but is unlikely to rise much more. With trailing_profit set to 0 the bot will not wait for a price drop at all but will sell immediately when the Trigger% condition becomes true.

Activating panic_sell_enabled for the pair works too, but you may sell for a much lower price than you expect when that happens as the bot's priority is to get rid of it regardless of profit and order book situation.

Please read the Wiki. This is all there. Nothing new is needed.
