### ISSUE TITLE
[Feature Request] Strategies Back testing 

### ISSUE THREAD

**Issue by slimgit** [taniman/profit-trailer#863]
It would be really helpful if you add a back testing on old market data.  It would help in refining strategies/settings to maximise profit. Thanks!

**Comment by Macflurry26** [comment]
Ha, your second request that I've had the same thoughts for, lol.

If a data set could be captured covering various market states like big booms/drops, small rises and dips back to back etc then highlight on a chart where the bot would trail, buy and sell it would be great for tweaking settings to behave exactly as you want.

**Comment by slimgit** [comment]
It's good that I'm no the only one having these ideas lol.

Exchanges provide historical market data, it should be easy to download the data to a database and run your bot settings against it. In fact there are a couple of bots out there that does just that.

**Comment by a7777777v** [comment]
Here is a good back testing example https://github.com/askmike/gekko

**Comment by masterpropper** [comment]
@a7777777v do you implemented all pt strategies into gekko yet? maybe you would share them?

**Comment by l2trace** [comment]
+1

**Comment by Paraoxysmal** [comment]
You can already do this but involes playing with your computers hostfiles and acting as an API, delivering old info as new and letting it pretend trade. To be perfectly honest *practicing* on old data is like taking a math test you already know the answers for. Markets tend to repeat history but not enough so that your strategy should be so held in history.

**Comment by LRpz** [comment]
+1

**Comment by YoJeff** [comment]
This is a huge undertaking/direction change for PT.   Not right now...
