### ISSUE TITLE
[Feature Request] EMACROSS Sell Strategy 

### ISSUE THREAD

**Issue by bitring2011** [taniman/profit-trailer#884]
EMA_1=200
EMA_2=50

Sell when EMA_2 crosses below EMA_1

**Comment by Tank33au** [comment]
hmm I dont think you'd want to use emacross for a sell strat.. it lags hell to be used as an exit strategy.

**Comment by bitring2011** [comment]
200/50 is a longer term strat (golden cross), but does provide an excellent sell signal

**Comment by DragonBtc93** [comment]
Please give this too us and add a minimum profit

**Comment by DragonBtc93** [comment]
You can set the gain at a neg. I set mine to -100

**Comment by SgtBatten** [comment]
@DragonBtc93 does it function correctly? Good to know if it's possible.

**Comment by DragonBtc93** [comment]
It has worked for me

**Comment by YoJeff** [comment]
v2.x allows EMACROSS as a sell strategy.

If any/all of this request is still valid, resubmit in the issues github here:  https://github.com/taniman/profit-trailer-enhancements/issues

**Comment by aludden** [comment]
That is not really true. Yes, you can set it, but since GAIN is mandatory, if the cross happens just below a gain (which happens quite often), PT does not sell and you're left with a bag. The whole point of selling on EMACROSS is to avoid bags (even if it results in a small loss). It should act like Stop Loss does. This seems to be a 
popular request, there are several with different wordings, so I'm not alone. Thanks!

**Comment by DragonBtc93** [comment]
Set your gain to -100

**Comment by aludden** [comment]
Gain can only be a positive number.

**Comment by SgtBatten** [comment]
Did you try it? PT isn't designed to sell for a loss. But it might work. Please advise

**Comment by YoJeff** [comment]
Feel free to continue the conversation here, but either way -- it's not a bug.   If there is a feature request still -- post in the repo linked above.

**Comment by DragonBtc93** [comment]
Yes I run mine with -100 and it works fine

**Comment by SgtBatten** [comment]
Thanks dragon

**Comment by aludden** [comment]
I didn't try it, because the wiki says that it has to be zero or greater. I will try it now. Thanks!

**Comment by DragonBtc93** [comment]
Yes I have had a few losses. I have some decent results but I hate to say but some issues with PT has been holding me back.

**Comment by aludden** [comment]
@DomsterKB Sorry, haven't tried it yet, need to set up another bot for it first

**Comment by aludden** [comment]
@DragonBtc93 Thanks for the info

**Comment by aludden** [comment]
OK, I did try it, and you're right, Dragon, it does work. Wish the wiki would be clearer about that. As far as the EMACROSS strat for selling, it works out really bad. Most everything turns out negative. There seems to be a big gap and/or lag between the crossing time and the selling. Looking at the chart, it should work, but it doesn't. Of course, if everything is going up, it might work, but in a sideways market like this it doesn't.
