### ISSUE TITLE
Feature Request: If min buy will exceed setting of min buy balance, then stop looking for pairs to buy

### ISSUE THREAD

**Issue by machyy1** [taniman/profit-trailer#915]
A lot of extra calls to the exchanges are being made checking for new pairs (ie in the pairs log), when the settings prevent buying at that time due to not having enough balance.  This shows up in the log as:

NormalStrategyRunner - You are not allowed to buy ICXBTC. Buy will exceed min buy balance 0.095154. BAL: 0.00515426 - MC: 0.0025

My request is to have PT behave the same as it does when you are at or over the max pairs, which is nothing is shown in the pairs log.

**Comment by a7777777v** [comment]
I don't think thats a good idea. Why? The point is that you might make a sale, go over your balance, and then you don't have any pairs ready to buy. I would much prefer that I have possible buys queued up ready to pull the trigger the second my balance goes up from a sale. Rather than waiting after a sale to see the buys. By seeing the open buys I'm also seeing where I am missing trades because my balance is too low. I used this to tune how much I had available to PT to make max trades/day.

**Comment by YoJeff** [comment]
What if the price is right on the fence, and it drops enough to allow the purchase?
What if a new pair becomes tradeable because of volume filter?
What if you change the allowed number of pairs?

Any of these could allow a sale within the allowed buy balance.   PT has to keep watching.
