### ISSUE TITLE
Delay in updating data causing automatic rebuy

### ISSUE THREAD

**Issue by joeyoon80** [taniman/profit-trailer#927]
I just saw an issue, which I dont know if it is only affecting the current version 1.2.6.14 or before. I have max pairs set to 3 pairs only. When I have 3 pairs (lets assume X,Y,Z, and Z being the latest pair bought), possible buy log blanks out to 0. Subsequently if Z pair sells first, the possible buy log reappears, but the data is from before it blanked out. This causes the bot to think the Z pair that I sold most recently is still true trailing and it executes a buy again.

If possible, can please add a small delay when the possible buy log returns after post sell to refresh its pricing and tracking data to the latest before pursuing to buy again.

**Comment by shunsing22** [comment]
I'm seeing this as well with using EMASPREAD.  It may be related, maybe not.  I've only noticed this since being on v14 and it has happened 3 times in last 24 hours, when I've not noticed this before.  

I'm using the following;
EMASPREAD
buy: -0.95
trail: .215

The bot will buy at the correct spot (well that's another issue for another time since the trail doesn't seem to work accurately either, but...), then when the bot makes the sell, it immediately rebuys the same coin for more than what it sold it for.  

My theory:  
What I think is happening is that the bot is remembering the lowest water mark for that coin, let's say it was at a -1.10.  The bot buys at some number higher than that, say -1.05, then makes the sell at -1.00.  The bot is seeing that now the coin is at -1.00 spread which is still lower than the buy value of -0.95, and less than the buy trigger, which is still pinned at -1.10, so it buys again.  I've noticed that the buy trigger gets "pinned" there at that water mark for a long time, if not forever and it has acted in weird ways that I didn't expect because of it.  I sort of wrote it off as a visual GUI misrepresentation or the bot being lazy with updating the GUI etc. but the behaviour is matching.

This behavior matches the description by OP.  Please help.

**Comment by taniman** [comment]
The bot does not remember data. everything is read real time before doing a buy. 
So unless you can show that this coin Z it bought again was not really true trailing than I cannot investigate further.

**Comment by shunsing22** [comment]
I'm not sure how to prove that, but I'll start with posting the logs from the buy, sell, and rebuy.  Hope this helps.

**# First Buy:**
2018-02-01 16:20:08 INFO ProfitTrailerService - Buy order for TRIGBTC -- {"symbo
l":"TRIGBTC","orderId":2260001,"clientOrderId":"GJkoRRqmcX1qKwFR51x39B","transac
tTime":1517530808756,"price":"0.00023790","origQty":"10.51000000","executedQty":
"10.51000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}

2018-02-01 16:20:14 INFO ProfitTrailerService - Get order information -- {"symbo
l":"TRIGBTC","orderId":2260001,"clientOrderId":"GJkoRRqmcX1qKwFR51x39B","price":
0.00023790,"origQty":10.51000000,"executedQty":10.51000000,"status":"FILLED","ti
meInForce":"IOC","type":"LIMIT","side":"BUY","stopPrice":0E-8,"icebergQty":0E-8,
"time":1517530808756}
2018-02-01 16:20:14 INFO NormalStrategyRunner - Normal Pair - EMASPREAD bought -
- currency pair TRIGBTC - BV -0.95, BVL 0.0, MTP 4, TTP 4

**# Whole next Sell and Re-Buy sequence:**
2018-02-01 16:25:04 INFO ProfitTrailerService - Sell order for TRIGBTC sold amou
nt 10.510000 for price 0.000241 -- {"symbol":"TRIGBTC","orderId":2260609,"client
OrderId":"H94nZyTncpnKADrHugGYo8","transactTime":1517531104240,"price":"0.000240
60","origQty":"10.51000000","executedQty":"0.00000000","status":"EXPIRED","timeI
nForce":"IOC","type":"LIMIT","side":"SELL"}
2018-02-01 16:25:07 INFO ProfitTrailerService - DCA Heartbeat
2018-02-01 16:25:10 INFO ProfitTrailerService - Get order information -- {"symbo
l":"TRIGBTC","orderId":2260609,"clientOrderId":"H94nZyTncpnKADrHugGYo8","price":
0.00024060,"origQty":10.51000000,"executedQty":0E-8,"status":"EXPIRED","timeInFo
rce":"IOC","type":"LIMIT","side":"SELL","stopPrice":0E-8,"icebergQty":0E-8,"time
":1517531104240}
2018-02-01 16:25:22 INFO ProfitTrailerService - Sell order for TRIGBTC sold amou
nt 10.510000 for price 0.000241 -- {"symbol":"TRIGBTC","orderId":2260785,"client
OrderId":"maY2Ii5M3mWU7Bwiw23sH0","transactTime":1517531122558,"price":"0.000240
70","origQty":"10.51000000","executedQty":"10.51000000","status":"FILLED","timeI
nForce":"IOC","type":"LIMIT","side":"SELL"}
2018-02-01 16:25:28 INFO ProfitTrailerService - Get order information -- {"symbo
l":"TRIGBTC","orderId":2260785,"clientOrderId":"maY2Ii5M3mWU7Bwiw23sH0","price":
0.00024070,"origQty":10.51000000,"executedQty":10.51000000,"status":"FILLED","ti
meInForce":"IOC","type":"LIMIT","side":"SELL","stopPrice":0E-8,"icebergQty":0E-8
,"time":1517531122558}
2018-02-01 16:25:35 INFO ProfitTrailerService - Buy order for TRIGBTC -- {"symbo
l":"TRIGBTC","orderId":2260843,"clientOrderId":"SEwP6LDdVwcclRrdeHa9rx","transac
tTime":1517531135194,"price":"0.00024100","origQty":"10.37000000","executedQty":
"10.37000000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}

2018-02-01 16:25:41 INFO ProfitTrailerService - Get order information -- {"symbo
l":"TRIGBTC","orderId":2260843,"clientOrderId":"SEwP6LDdVwcclRrdeHa9rx","price":
0.00024100,"origQty":10.37000000,"executedQty":10.37000000,"status":"FILLED","ti
meInForce":"IOC","type":"LIMIT","side":"BUY","stopPrice":0E-8,"icebergQty":0E-8,
"time":1517531135194}
2018-02-01 16:25:41 INFO NormalStrategyRunner - Normal Pair - EMASPREAD bought -
- currency pair TRIGBTC - BV -0.95, BVL 0.0, MTP 4, TTP 4

Thanks!

**Comment by YoJeff** [comment]
Are there any exchange fails inbetween any of that?    It seems to say that right after the sale, the SPREAD was -0.95.

**Comment by shunsing22** [comment]
The spread was still south of -0.95 when the sale and rebuy happened.  I suspect that is why it happened, but I also expected there to be some sort of reset on the trigger so that it would trail again, that's the part I don't think is happening.  I don't know of any or how to check if there were any exchange fails.  What I pasted above is all the parts of the logs, no lines were left out in between there.
