### ISSUE TITLE
[BUG] EMA Spread buying outside of specified values

### ISSUE THREAD

**Issue by eFlowMedia** [taniman/profit-trailer#947]
Hello.  I have noticed that my bot is buying at times that are outside of the specified range.  I am seeing exactly what ticket #783 from ACETyr is seeing.  I will explain in detail on multiple coins what is happening.
To prefece this, I would like to give you my initial settings to see what we are dealing with.

My EMA Settings are
EMA_period = 300 (5 Minute Candles)
EMA_1 = 24
EMA_2 = 6

My Buy Settings are
ALL_buy_strategy = EMASPREAD
ALL_buy_value = -0.89
ALL_trailing_buy = 0.215
ALL_max_buy_spread = 1

So the coin needs to go -0.89 before it starts trailing the buy.  If it goes up .215 then buy it immediately.
![2018-02-01 11 28 33 am](https://user-images.githubusercontent.com/16480031/35698839-19a9edde-0743-11e8-90c6-3fade6ee5ad1.jpg)

As you can see from the chart here, the EMAs (6 & 24) and Time Frame (5 min) are set correctly.

The most the EMA2 went down from EMA1 is -.59%.  It never got to the required -.89 value in order to start trailing for the buy, but it ended up trying to purchase at .0417000.

Here is a screen shot in Binance that is showing the purchase order.
![2018-02-01 11 31 29 am](https://user-images.githubusercontent.com/16480031/35699010-9d4cfa46-0743-11e8-9905-931bb0b75390.jpg)

Here is a screen shot in Binance showing the largest spread and the prices.
![20](https://user-images.githubusercontent.com/16480031/35699581-5a13fe1c-0745-11e8-8a9d-4022daeebad8.jpg)
![22](https://user-images.githubusercontent.com/16480031/35699586-5e242784-0745-11e8-9493-b9e579f2a813.png)

As you can see Binance shows the highest EMA being .041857 with the lowest .041563 which is not the .89% required spread to buy.

And here is the log from PT
2018-02-01 19:00:32 INFO ProfitTrailerService - Buy order for ZECBTC -- {"symbol":"ZECBTC","orderId":7443682,"clientOrderId":"mLCvLuRWmXmu83lgbwKrI1","transactTime":1517511632035,"price":"0.04170000","origQty":"0.08600000","executedQty":"0.00000000","status":"EXPIRED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}
2018-02-01 19:00:37 INFO ProfitTrailerService - Get order information -- {"symbol":"ZECBTC","orderId":7443682,"clientOrderId":"mLCvLuRWmXmu83lgbwKrI1","price":0.04170000,"origQty":0.08600000,"executedQty":0E-8,"status":"EXPIRED","timeInForce":"IOC","type":"LIMIT","side":"BUY","stopPrice":0E-8,"icebergQty":0E-8,"time":1517511632035}

I can understand there can be some discrepancies based on whether you use open or close for the candles, but even taking that into account, I am still not seeing it get to the required drop to buy, but its still purchasing. 

This is one example of many that I have found.  I will draw up the charts for the various others for reference.

**Comment by eFlowMedia** [comment]
Here is another example where it bought before it hit the required -0.89.  
![2018-02-01 12 09 07 pm](https://user-images.githubusercontent.com/16480031/35700788-d5a95d30-0748-11e8-9218-1b9fc1a16bc0.jpg)

![2018-02-01 12 10 20 pm](https://user-images.githubusercontent.com/16480031/35700807-e35700ae-0748-11e8-9585-ce519e803187.jpg)

It actually looks like it was reversed as the EMA 1 was Higher than EMA 2 by 1% right before it bought.
![2018-02-01 12 11 25 pm](https://user-images.githubusercontent.com/16480031/35700897-24c7674a-0749-11e8-9866-4f9aa25ac790.jpg)

**Comment by eFlowMedia** [comment]
Here is another example where it did not buy correctly.  In this example, the minimum spread was met but it bought at a price above both EMAs

![2018-02-01 12 37 04 pm](https://user-images.githubusercontent.com/16480031/35702118-1247b1fc-074d-11e8-83f4-104a6bb1fefc.jpg)

![2018-02-01 12 39 41 pm](https://user-images.githubusercontent.com/16480031/35702140-1eff63c2-074d-11e8-9e94-88928ae932fd.jpg)

**Comment by smoochy** [comment]
Just an idea: are you also using PT Feeder? This sets different settings for each coin which can be different from your general settings.
Would you mind checking your pairs.properties for something like:

`#------------------BTC/BCD------------------
# BCDBTC has been set to SELL ONLY mode
# Price change (60): 0.52%
# Price change (1440): 20.84%
# Upside volatility: 1.15%
# Downside volatility: 0.79%
# Sell Only Mode Reasons:
 # Longer term price change config
# Price trend config
# Pair has sell only mode

BCDBTC_trading_enabled = true
BCDBTC_trailing_profit = 0.179
BCDBTC_DCA_enabled = -2
BCDBTC_sell_value = 0.6255
BCDBTC_sell_only_mode = true
#------------------------------------`

**Comment by eFlowMedia** [comment]
Thanks for trying to help me with this.

Nope not running feeder.  I just turned the bot back on again, and it just did another wrong buy...


![2018-02-01 03 19 20 pm](https://user-images.githubusercontent.com/16480031/35708515-6766fef2-0763-11e8-884e-2617b78704bd.jpg)

These are the only settings I have in Pairs

ALL_buy_strategy = EMASPREAD
ALL_buy_value = -0.89
ALL_trailing_buy = 0.15

There are no coin specific values.

Here is the log
2018-02-01 15:07 -08:00: 2018-02-01 23:07:31 INFO ProfitTrailerService - Get order information -- {"symbol":"DGDBTC","orderId":4407483,"clientOrderId":"0kO3jr4pi2gdz83w64H4R4","price":0.02918900,"origQty":0.12000000,"executedQty":0.12000000,"status":"FILL:"BUY","stopPrice":0E-8,"icebergQty":0E-8,"time":1517526445802}
2018-02-01 15:07 -08:00: 2018-02-01 23:07:31 INFO NormalStrategyRunner - Normal Pair - EMASPREAD bought -- currency pair DGDBTC - BV -0.89, BVL 0.0, MTP 12, TTP 5

Just because it the spread was 3% shouldnt mean it should buy the coin at any value.  The buy price should at least be lower or equal to the minimum buy -0.89.  Here it bought .11% UP from the SLOW ema line
![2018-02-01 03 29 35 pm](https://user-images.githubusercontent.com/16480031/35708909-2ab3b1a6-0765-11e8-8a91-7139c0199a18.jpg)

![2018-02-01 03 33 04 pm](https://user-images.githubusercontent.com/16480031/35708918-36a27e34-0765-11e8-9b17-6bb41ef511bd.jpg)

**Comment by shunsing22** [comment]
At one point in time I was seeing numbers in the current value for coins (possible buy log) and the fix was to run some commands on the Windows server to sync time.  If your current values do not match what you see in tradingview, I'd suggest trying that.

Windows: 
     net start w32time
     w32tm /resync

**Comment by eFlowMedia** [comment]
@shunsing22  Thanks for taking the time to help with the problem.  The charts on trading view and binance match up perfectly, theres no problem there.  I was just using trading view to illustrate the  problem as it is easier to draw on it, measure percentages etc..

**Comment by YoJeff** [comment]
Here is another thought.   As they say, hind sight is 20/20.

On that first chart, ZEC...  On the bar that dipped down to 411.     What do you calculate the spread was at that moment in time?

**Comment by eFlowMedia** [comment]
@YoJeff   -.61%
Here it is blown up...
![2018-02-01 06 30 53 pm](https://user-images.githubusercontent.com/16480031/35713797-2e238b86-077e-11e8-9d0e-f9a82d2f1bfd.jpg)

**Comment by YoJeff** [comment]
Thats not the low.

**Comment by eFlowMedia** [comment]
Thats the ema line from the combined prices of the whole 5 min candle.  Isnt that what it calculates from?  % difference between the 2 EMAs.

From the low is -1.68%
![2018-02-01 06 35 31 pm](https://user-images.githubusercontent.com/16480031/35713907-bd50c26a-077e-11e8-8941-aeb86f36793a.jpg)

**Comment by YoJeff** [comment]
Time doesn't unfold in neat 5m chunks.   Take that chart, rewind to the exact point where that low was reached and tell me the values.   That's what the bot sees.

**Comment by eFlowMedia** [comment]
Sure, no problem.  Thanks for the help.
The low was .041127, the next candle low was .041345.
Does the bot calculate the EMA based on the open price, close price or any other value(Average of all the prices in the time)?

**Comment by YoJeff** [comment]
Historical bars would be the close, but the current bar is based on current price.

My point is the 'hard right edge' as they call it -- unfolds in real time.   That right bar goes up and down.  The averages go up and down.  The spread goes up and down.    Right up to the point the 5m mark is passed, then it's packaged up neatly, locked down and shifted one candle left.

So while it's tempting to armchair quarterback the bot's performance based on nice tidy 5m closing prices.   In real time it's not quite as easy or clean.

And if I squint at the chart without breaking out a calculator -- this doesn't look egregious.

Your charts show you are 2/3 of the way there based on closing prices.   But the wick of that candle is at least the height of your spread.  So getting the other 1/3 there as it unfolds isn't unreasonable.

**Comment by shunsing22** [comment]
Maybe this is a silly question but whats the point of the indicators being 300 seconds if the bot is using real time anyway?  Maybe I'll end up answering my own question here, but would it be to just set the spread, then once that's reached, the trail is real time?  Assuming that is true, would the trail be the set trail % from the lowest low in the last candle?  In the last what?  

I've played with that trail and used as high as .215 like OP, and as low as .04 to try and get it to buy sooner, in either case, according to the candles, it waits much, much longer to trigger the buy than you would think.

**Comment by eFlowMedia** [comment]
@YoJeff Thank you for your insight.  That makes complete sense.   In this case, it was pretty close I can understand why it could happen.

What are your thoughts on the 2nd chart (VEN)?

**Comment by YoJeff** [comment]
Sunsing, 

What's the alternative?  To only trade every 5 minutes after the bar is fully formed?

**Comment by shunsing22** [comment]
@YoJeff, I don't have a suggestion really.  I'm just trying to better understand so I can better develop a strategy that does what I expect.  I greatly appreciate you guys and the community, truly.  I don't know how to add pictures here, but I just had a buy of NEO at 1:04pm EST @ .013709 after it fell to a low of .013305 at 12:56pm (Binance), a difference in bottom and buy of 3.06%.  The window of time for this was 8 min apart.  My trail is set at .215.  The difference between the bottom and top of the candle at 12:56pm (1min candle) is 1.28%, which is well outside the trigger of .215.  Hopefully you could see the confusion with that?  In this particular case, the bot bought the coin when it was at it's peak which isn't really what was hoping for or expected.

To simplify my previous question and take one thing at a time, I suppose what I'm after is what is the bot using as the number to subtract the trail from in order to decide if it's time to buy?  We know the trail, we know the current price, but from how long ago is the "low"or buy trigger that the bot is using in that calculation.  From the last candle as defined in the indicators file, or some other window of time?  The GUI shows a buy trigger of lowest it's ever been, that number doesn't change.  Is it "remembering" when it shouldn't, or is that just a visual GUI type of issue and isn't representing the actual new buy trigger because that changes too often to keep the GUI updated?  In another ticket, I suggested there may be a bug with the bot "remembering" the buy trigger because I've had multiple times now where the bot would buy a coin I just sold for more than what I sold it for.  It would do this only a few seconds apart, and it hadn't had time to trail yet, nor was the diff in price more than the trail.  The ticket was closed without waiting for more info and he said it wasn't a bug because the bot doesn't remember anything...  but it must if it does trailing, right?  I feel like I'm starting to offend by asking questions, honestly, I'm not here to piss you off, I'm just trying to help and understand.  If I can help find a bug cool, if I'm completely off base and it's an education problem on my part, cool.

**Comment by YoJeff** [comment]
There may be a bug in here, I'm not sure.   But to evaluate buys based on historical 5m pristine bars is not really fair to the bot.    You need to account for what the values were at the whole range of prices within that 5m period.   Even then that does not necessarily mean the bot 'saw' that low price.

Since I don't use SPREAD or CROSS strategies, I'm not as familiar with everything.

But I can say this.

I've been running SMAGAIN lately.   I store detailed metrics from both the exchanges and PT in a database.   The SMAGAIN values I calculate based on exchange values very, very closely mimic the values PT calculates.

With respect to the trail, the bot must reach (and stay above/below) buy/sell_value + trail.  Then it trails and attempts to buy/sell after it wiggles > trail.   The buy/sell is still valid unless the price drops below the buy/sell_value.

Slippage is always a factor in any market.   Always check your logs for settings related issues (not enough volume, spread too big, etc).

You aren't offending -- no worries.    Feel free to ping me in discord as well.

**Comment by shunsing22** [comment]
thank you Sir!  I greatly appreciate it and I'll now go and try and digest what you've shared lol.  I will update the other ticket with the sort of related, but different issue with the logs I just pulled.  Hopefully it will get reopened once I add more info.  thx again!

**Comment by shunsing22** [comment]
other ticket link for reference:  https://github.com/taniman/profit-trailer/issues/927#event-1454664421

**Comment by wartimekillers** [comment]
i set my trailing buy in negatives, and i think its buy as i expected
