### ISSUE TITLE
My Possible Buy Log Is 20 But all are showing in false

### ISSUE THREAD

**Issue by CryptoLover4** [taniman/profit-trailer#964]
When I am running my bot on my personal laptop then possible buy log is 20 and few are in (true trailing) but when I am running my bot on my VPS with exact settings then here it is showing possible buy log is 20 but all are in (False). Those coins are showing true trailing on my personal Pc These coins are also showing False on my VPS. For this cause when I am running my bot on my VPS its not buying any coin, only selling previously bought coins. So please help me. (sorry for my bad English)
Thank you

**Comment by YoJeff** [comment]
Please visit support, this is for bugs only.
https://wiki.profittrailer.io/doku.php/start

**Comment by BobProTrai** [comment]
Hi together
I have the same issue. Today my PT was frozen and I have had to restarted it. It is also running on a VPS. But since the restart in my PBL under "Buy Strat" is EMAGAIN (false). I can not find the issue. The days before it runs properly. 
Did somebody find out how to fix this issue?

Thanks a lot

![bildschirmfoto 2018-02-25 um 18 50 18](https://user-images.githubusercontent.com/36821978/36644733-156a4f78-1a5f-11e8-86fc-06aa33be46ac.png)
