### ISSUE TITLE
DCA not working

### ISSUE THREAD

**Issue by ThecRw** [taniman/profit-trailer#978]
This is related to issue described here:
https://github.com/taniman/profit-trailer/issues/851

This bug is not fixed on version 1.2.6.14 and I got no reply or comments when I opened the previous issue. This is happening on Binance

DCA is not working as intended. A coin is bought and after a few moments DCA buys all max_buy_times available without the coin dropping the minimum percentage. It literally consumes all available balance, not leaving space for more DCA´s.

I have a case (log attached) again today were the bot bought DGDBTC and bought it again 3 times afterwards doing DCA, however, the 3% drop in price was not observed.

This is my conf in DCA properties:

max_cost = 0
max_buy_times = 3

buy_strategy = LOWBB
buy_value = 0
buy_trigger = -3
trailing_buy = 0.2

Log file is:
[03-03-2017.txt](https://github.com/taniman/profit-trailer/files/1691566/03-03-2017.txt)

**Comment by taniman** [comment]
Can you provide your DCA.properties file?

**Comment by taniman** [comment]
sorry, see it now in the comment :)

**Comment by taniman** [comment]
@ThecRw I am missing a piece of between 08:29:21 and 08:29:45

**Comment by ThecRw** [comment]
Hi mate

Thanks for having a look at this ;)

I can definitely provide you with any information you need.

Below the complete log since the bot was started yesterday + dca.properties + pairs.properties (just in case).

Let me know if there is anything else you need. Hopefully you are going to find the bug.

Thanks for the great work
[DCA.properties.txt](https://github.com/taniman/profit-trailer/files/1691780/DCA.properties.txt)
[PAIRS.properties.txt](https://github.com/taniman/profit-trailer/files/1691781/PAIRS.properties.txt)
[03-03-2017-02.txt](https://github.com/taniman/profit-trailer/files/1691782/03-03-2017-02.txt)

**Comment by Stein276** [comment]
Don't you need buy triggers in your DCA file?

Example

buy_strategy = ANDERSON
buy_style = DOUBLEDOWN
buy_trigger_1 = -3.5
buy_trigger_2 = -5.5
buy_trigger_3 = -8.5

**Comment by ThecRw** [comment]
Hi @Stein276 

I´m not using ANDERSON, I´m using LOWBB

buy_strategy = LOWBB
buy_value = 0
buy_trigger = -3
trailing_buy = 0.2

**Comment by Stein276** [comment]
Sorry about that, ignore my message :)

**Comment by commandocrypto** [comment]
Same issue here. DCA didn't record purchases and kept buying until it spent all my budget... Now I am stuck with $4,000 of LTC??? And $2000 of NEO. Also, it bought and sold NEO so many times, that it lost track of the average price of the left over coins. 

See attached log, DCA, and Pairs files. 

Started to have issues on the log at 1630 with PT marking orders as expired, but significant quantities being purchased. Then the meltdown starting at 1723 when the bot spent $7,000 in 12 minutes. Then at 1738, it tried to frantically sell NEO over and over until it lost track of the price average to make a profit. I am pretty it was not selling at a profit here...

It looks like every purchase had an error that prevented the recording of the purchase, even thought it bought the pairs:

2018-02-07 17:23:10 ERROR ProfitTrailerService - Error occured in buy, message ERROR: -2013, Order does not exist., result: {"symbol":"LTCUSDT","orderId":7298642,"clientOrderId":"78jeILNJDBGPbm6nyqcbN0","transactTime":1518042181792,"price":"145.50000000","origQty":"0.67558000","executedQty":"0.67558000","status":"FILLED","timeInForce":"IOC","type":"LIMIT","side":"BUY"}

This is a significant bug, I mean we are talking the fundamental function of the bot here. REALLY need to know if this is a PT code issue, or VPN issue, or Binance issue. I shut down the bot in the last version because it was buying pairs and not tracking them. Now in this version, the bot keeps buying until it spends all your funds. 

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1705318/ProfitTrailer.log)
![img_0982](https://user-images.githubusercontent.com/35410651/35950275-be6e6e1c-0c43-11e8-840e-6b68f9e3ec08.jpg)
![img_0981](https://user-images.githubusercontent.com/35410651/35950283-c328ff58-0c43-11e8-8ed0-7e38aee11371.jpg)
[PAIRS.txt](https://github.com/taniman/profit-trailer/files/1705319/PAIRS.txt)
[DCA.txt](https://github.com/taniman/profit-trailer/files/1705320/DCA.txt)

**Comment by commandocrypto** [comment]
Running v1.2.6.14

**Comment by ThecRw** [comment]
@commandocrypto I´ve been running Ver:  1.2.6.15 for almost 3 days now and the issue seems to be resolved. I suggest you update your PT and let us all know if you still see this issue.

Hope it helps!
