### ISSUE TITLE
[Feature Request] Trailing Stop Loss

### ISSUE THREAD

**Issue by Ghostdoge** [taniman/profit-trailer#988]
I would like to setup trailing stop losses for individual coins after I buy manually from exchanges.

I looked through the stop loss options on the wiki, and could not see any trailing stop loss options at all.

Thank you.

**Comment by alexdolli** [comment]
[Pairname]_trailing_profit = %
Put that in your pair.properties file and DCA.properties.
If I'm wrong, please someone correct me by any means. I'm new here, too.

**Comment by YoJeff** [comment]
Please use support.

**Comment by bverkron** [comment]
I second this request. @alexdolli that will not trail the price up automatically. You'd have to manually adjust that each time.

Trailing stop loss would automatically most the stop loss up as the price increased.  This should be safer than only relying on a gain / trailing sell strategy because the stop loss order would already be on the exchange.  No risk of having a cancelled order due to timeout, connectivity or data refresh timing issue preventing a sell order from being submitted, etc.

Trailing stop loss could actually be essentially used as a sell strategy if you, for example, use a highbb strategy and buy near the start of a price rise.  You could have the trailing stop coming up behind the price rise as a safety and if the higher gain strategy didn't get triggered and / or there was a sudden price dive / correction it would fall back to the stop loss and sell for profit (assuming it had moved up enough).
